### DISCUSSION TITLE
[BUG] PHP Fatal error:  Uncaught RuntimeException: Unable to create the "cache" directory

### DISCUSSION THREAD

**Discussion by pbek** [tobybatch/kimai2#457] [General]
**Describe the bug**
In my docker log I'm getting a:
```
PHP Fatal error:  Uncaught RuntimeException: Unable to create the "cache" directory (/opt/kimai/var/cache/prod). in /opt/kimai/vendor/symfony/http-kernel/Kernel.php:686\nStack trace:\n#0 /opt/kimai/vendor/symfony/http-kernel/Kernel.php(593): Symfony\\Component\\HttpKernel\\Kernel->buildContainer()\n#1 /opt/kimai/vendor/symfony/http-kernel/Kernel.php(136): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#2 /opt/kimai/vendor/symfony/http-kernel/Kernel.php(196): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#3 /opt/kimai/public/index.php(32): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#4 {main}\n  thrown in /opt/kimai/vendor/symfony/http-kernel/Kernel.php on line 686
```
after a docker pull since about 12h ago when accessing my kimai2 instance and the instance was inaccessible.

I think https://github.com/tobybatch/kimai2/commit/99dea366424a6e59da3c1ae71f48d9fc94f07eac#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R254 could have done this.

I'm only reporting in case someone else has this too.

I couldn't fix this by just setting the permissions for the `/opt/kimai/var` or `/opt/kimai/var/cache` manually, they were reset. Not even make them world writable did fix it, I just got a different error 500 (with no further error in docker log, I had to visit the kimai2 logs in the log directory).
I could only **fix** this by setting the **env vars to 33** (www-data), 1000 (www-kimai) didn't work for me:

```yaml
      - USER_ID=33
      - GROUP_ID=33
```

All other files/dirs were already owned by `www-data`.

**Docker compose file (with passwords redacted)**

```yaml
  kimai:
    image: kimai/kimai2:apache
    depends_on:
      - kimai-mysql
    volumes:
      - kimai-var:/opt/kimai/var
      - ./kimai/local.yaml:/opt/kimai/config/packages/local.yaml
    restart: unless-stopped
    networks:
      - kimai
      - traefik
    environment:
      - TZ=Europe/Vienna
      - TRUSTED_HOSTS=localhost,127.0.0.1,my-server.com
      - ADMINMAIL=my@email.com
    env_file:
      - ./kimai/variables-kimai.env
    labels:
      # I had to turn off the Cloudflare proxy, because PATCH requests didn't go through to stop time entries
      - traefik.http.routers.kimai.rule=Host(`my-server.com`)
      - traefik.http.routers.kimai.tls.certresolver=default
      - traefik.http.routers.kimai.tls=true
      - traefik.http.services.kimai.loadbalancer.server.port=8001
      - traefik.docker.network=server_traefik
```
