### DISCUSSION TITLE
Regarding latest docker image update

### DISCUSSION THREAD

**Discussion by hsachan22** [tobybatch/kimai2#509] [Q&A]
I was using apache tag for running kimai2, but today it didn't worked. I checked dockerhub and found out that image was updated 17 hours ago. So, can anyone help me which tag to use for properly running the image?

**Comment by tobybatch** [comment]
What is your error? We just jumped from 1.x to 2.x

**Reply by hsachan22** [reply]
```
kimai-1  | [Wed May 24 12:11:45.436078 2023] [mpm_prefork:notice] [pid 83] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
kimai-1  | [Wed May 24 12:11:45.436166 2023] [core:notice] [pid 83] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
kimai-1  | [Wed May 24 12:12:01.180183 2023] [php:error] [pid 84] [client 127.0.0.1:45038] PHP Fatal error:  Uncaught Error: Class "Symfony\\Component\\Runtime\\SymfonyRuntime" not found in /opt/kimai/vendor/autoload_runtime.php:16\nStack trace:\n#0 /opt/kimai/public/index.php(5): require_once()\n#1 {main}\n  thrown in /opt/kimai/vendor/autoload_runtime.php on line 16
kimai-1  | localhost:8001 127.0.0.1 - - [24/May/2023:12:12:01 +0200] "GET / HTTP/1.1" 500 185 "-" "curl/7.64.0"
```

**Comment by tobybatch** [comment]
And which tag are you running?

**Reply by hsachan22** [reply]
I am running "apache" tag

**Comment by tobybatch** [comment]
Can I see how you where starting that? docker run, compose whatever. There is a bug report template that exists so I don't have to ask all these question. :)

**Reply by hsachan22** [reply]
Here is the Dockerfile
```
FROM kimai/kimai2:apache

USER 0

COPY ./ /opt/kimai

WORKDIR /opt/kimai


RUN chown -R www-data:www-data . && chmod -R g+r . && chmod -R g+rw var/

RUN composer install --optimize-autoloader -n --no-scripts

RUN composer require laminas/laminas-ldap --optimize-autoloader -n --no-scripts

COPY ./setup.sh /setup.sh

RUN chown  www-data:www-data /setup.sh && chmod -R 744 /setup.sh

ENTRYPOINT [ "/setup.sh" ]

USER www-data

```

Anh this is my docker-compose.yml
```
version: "3.5"
services:
  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=kimai
      - MYSQL_ROOT_PASSWORD=kimai
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped

  kimai:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://kimai:kimai@sqldb:3306/kimai?charset=utf8&serverVersion=5.7
      - MAILER_FROM="test@gmail.com"
      - MAILER_URL="smtp://test:test@test587?auth_mode=login"
      - APP_ENV=dev
      - APP_SECRET=abcde
      - CORS_ALLOW_ORIGIN=^https?://localhost(:[0-9]+)?$
    ports:
      - 8001:8001
    volumes:
      - public:/opt/kimai/public
    restart: unless-stopped

volumes:
  public:
  mysql:
```
