### DISCUSSION TITLE
Docker-Compose.yml with Public Folder mounted

### DISCUSSION THREAD

**Discussion by empx92** [tobybatch/kimai2#552] [Q&A] [answered]
Hello Community.
I use a working compose file with the image kimai/kimai2:apache-latest.
I mounted the volumes:
 -./kimai_var:/opt/kimai/var 
 -./kimai_img:/opt/kimai/img
 
 which is working fine.
 As i need to Change some things in the public folder (eg. touch-icons and so on) i have an 502 bad Gateway error when mounting
  -./kimai_public:/opt/kimai/public
  
  Does anyone know about that issue or can't i simply mount other volumes than the two above?
  
  Best Regards

**Comment by tobybatch** [comment]
Can i see the whole compose file please?

**Reply by empx92** [reply]
```
version: '3.5'
services:
  mariadb:
    image: mariadb:latest
    container_name: kimai-db
    restart: unless-stopped
    hostname: kimai-db
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb_data:/var/lib/mysql
    command: --default-storage-engine innodb
    networks:
      - kimai
  kimai:
    image: kimai/kimai2:apache-latest
    container_name: kimai-app
    restart: unless-stopped
    hostname: kimai
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=192.168.1.90,localhost,${HOSTNAME}
      - ADMINMAIL=mail@admin.com
      - ADMINPASS=${KIMAI_ADMIN_PASSWORD}
      - DATABASE_URL=mysql://kimai:${MARIADB_PASSWORD}@mariadb/kimai
    volumes:
      - ./kimai_var:/opt/kimai/var
      - ./kimai_img:/opt/kimai/img
    ports:
      - '1234:8001'
    depends_on:
      - mariadb
    networks:
      - npm-nw
      - kimai
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5681:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - kimai
networks:
  kimai:
  npm-nw:
    external: true
```
