### ISSUE TITLE
[BUG] Updating to 1.8 can't acces

### ISSUE THREAD

**Issue by yayitazale** [tobybatch/kimai2#114]
**Describe the bug**
I launched the command 
`sudo docker-compose pull && sudo docker-compose up -d --build` to upgrade to 1.8 from 1.7
Migration of DB is clean but when kimai starts on log I see this:

```
Using Mysql DB
Wait for db connection ...
Connection established
Kimai2 ready
[Fri Apr 24 15:41:43.924257 2020] [core:warn] [pid 22] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Apr 24 15:41:43.927132 2020] [mpm_prefork:notice] [pid 22] AH00163: Apache/2.4.38 (Debian) PHP/7.3.10 configured -- resuming normal operations
[Fri Apr 24 15:41:43.927165 2020] [core:notice] [pid 22] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```

**Screenshots**
This is what I get.
![imagen](https://user-images.githubusercontent.com/6462849/80225326-35b5d680-864b-11ea-8177-e68e2ea61eb8.png)

**Comment by tobybatch** [comment]
Can you please include the other data asked for?

docker-compose.yml in this case.  A tail of the logs would be nice too.

**Comment by yayitazale** [comment]
Compose:

```
version: '3.5'
services:
  mydb:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=****
      - MYSQL_PASSWORD=****
      - MYSQL_ROOT_PASSWORD=****
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped

  kimai:
    image: kimai/kimai2:apache-debian-master-prod
    environment:
      - APP_ENV=prod
      # These are added to override the the DB URL from env when checking the DB status during start up.
      - DATABASE_URL=mysql://****:*****@mydb/kimai
      #- ADMINMAIL=kimai@example.com (ADMINMAIL=kimai@example.com)
      #- ADMINPASS=changeme
    depends_on:
      - mydb
    restart: unless-stopped
    ports:
      - 80:8001

volumes:
    mysql:

```

Logs:

```
Using Mysql DB
Wait for db connection ...
Connection established
first run - install kimai

Kimai installation running ...
==============================

Database kimai for connection named default already exists. Skipped.
                                                              
                    Application Migrations                    
                                                              

No migrations to execute.

 Rebuilding your cache, please be patient ...

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  


 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   


 [OK] Congratulations! Successfully installed Kimai 2 version 1.8 (stable)      

Kimai2 ready
[Mon Apr 27 08:36:03.677037 2020] [mpm_prefork:notice] [pid 27] AH00163: Apache/2.4.38 (Debian) PHP/7.3.10 configured -- resuming normal operations
[Mon Apr 27 08:36:03.677109 2020] [core:notice] [pid 27] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```
