### ISSUE TITLE
proxypass, redirect does not work

### ISSUE THREAD

**Issue by pixx1** [tobybatch/kimai2#121]
**Describe the bug**
Hi there! I'm facing some issues with that docker-compose and my proxypass (apache). I read the documentation but I may missed something ?! Or maybe a bug?

Something with the inner redirection seems not to work, like described here:  
> https://www.kimai.org/documentation/webserver-configuration.html

https://kimai.my-url.org redirects to http://kimai.catinabox.org/de/login
Error in web browser:
 > Not Found
> 
> The requested URL was not found on this server.
> Apache/2.4.41 (Ubuntu) Server at kimai.my-url.org Port 80

When I add manually the "https" after trying to connect to the website I can see the login screen. but this is not a correct behavior I would say. Also Login is not possible.

---
I tried to follow the instructions from the link above with no success. 

Since I'm using apache and not nginx I checked if my headers are correctly set, because I cannot use the config from the example:

```
GET / HTTP/1.1
Host: kimai.my-url.org
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Upgrade-Insecure-Requests: 1
DNT: 1
X-Forwarded-Proto: https
X-Forwarded-Port: 443
X-Forwarded-For: MY-DESKTOP-IP (not server)
X-Forwarded-Host: kimai.my-url.org
X-Forwarded-Server: kimai.my-url.org
Connection: Keep-Alive
```

The only thin I changed in my docker-compose file (beside passwords):
```
TRUSTED_HOSTS=nginx,kimai.my-url.org,localhost,127.0.0.1
TRUSTED_PROXIES=127.0.0.1,kimai.my-url.org,localhost
```

**To Reproduce**
Steps to reproduce the behaviour:
1. run docker-compose
2. Visit website
3. Error

---

**Desktop (please complete the following information):**
 - OS-Server: Ubuntu 20.04.
 - Docker version: 19.03.8
 - Docker compose version: 1.25.0

**Command used to run the container**
 - docker-compose up --build

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=???
      - MYSQL_ROOT_PASSWORD=???
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p??? ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    build: compose
    ports:
      - 8001:80
    volumes:
      - ./compose/nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:fpm-alpine-1.8-prod
    environment:
      - APP_ENV=dev
      - TRUSTED_HOSTS=nginx,kimai.my-url.org,localhost,127.0.0.1
      - TRUSTED_PROXIES=127.0.0.1,kimai.my-url.org,localhost,nginx
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=???
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix:latest
    environment:
      maildomain: kimai.local
      smtp_user: kimai:kimai
    restart: unless-stopped

volumes:
    var:
    public:
```

**Additional context**
My apache config:

```
<IfModule mod_ssl.c>
<VirtualHost *:443>

    ServerName kimai.my-url.org
    ProxyPass /  http://127.0.0.1:8001/
    ProxyPassReverse / https://127.0.0.1:8001/
    
    ProxyPreserveHost On	
    RequestHeader set X-Forwarded-Proto https
    RequestHeader set X-Forwarded-Port 443



	SSLCertificateFile .../fullchain.pem
	SSLCertificateKeyFile .../privkey.pem
	Include /etc/letsencrypt/options-ssl-apache.conf

    ErrorLog ${APACHE_LOG_DIR}/docker_kimai.log


</VirtualHost>
</IfModule>
```
I really hope someone can help me with this! 
Thanks a lot!
pix_1
