### ISSUE TITLE
Getting "500 Internal Server Error" on fresh install

### ISSUE THREAD

**Issue by lkathke** [tobybatch/kimai2#123]
Hello guys!
I am trying to install kimai2 via docker-compose without any success.
I alway get the "Oops! An Error Occurred - 500 Internal Server Error" error page.

![83135006-80f95400-a0e5-11ea-9d18-e2140f0eac23](https://user-images.githubusercontent.com/2429447/83165615-16a8d980-a10e-11ea-8956-7ad1fa4595c7.png)

My docker-compose.yaml is the following:

```
version: '3.5'
services:

  kimai_sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=JFH27E9P36bJTMBS
      - MYSQL_ROOT_PASSWORD=P86T5nHU1aLZV3Kt
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    # healthcheck:
    #   test: mysqladmin -pP86T5nHU1aLZV3Kt ping -h localhost
    #   interval: 20s
    #   start_period: 10s
    #   timeout: 10s
    #   retries: 3

  kimai_nginx:
    build: compose
    ports:
      - 8001:80
    volumes:
      - ./compose/nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - kimai_public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    # healthcheck:
    #   test:  wget --spider http://kimai_nginx/health || exit 1
    #   interval: 20s
    #   start_period: 10s
    #   timeout: 10s
    #   retries: 3

  kimai:
    image: kimai/kimai2:fpm-alpine-1.8-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=localhost
      - ADMINMAIL=test@test.de
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://kimai:JFH27E9P36bJTMBS@kimai_sqldb/kimai
    volumes:
      - kimai_public:/opt/kimai/public
      - kimai_var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    # healthcheck:
    #   test: wget --spider http://kimai_nginx || exit 1
    #   interval: 20s
    #   start_period: 10s
    #   timeout: 10s
    #   retries: 3

  postfix:
    image: catatnight/postfix:latest
    environment:
      maildomain: kimai.local
      smtp_user: kimai:kimai
    restart: unless-stopped

volumes:
    kimai_var:
    kimai_public:
```
Can someone give me a hint?
The container log looks normal:

![83135396-11379900-a0e6-11ea-99ac-a98f401adaf0](https://user-images.githubusercontent.com/2429447/83165680-2d4f3080-a10e-11ea-896d-002fe85a1a9b.png)

Thank you :))
