### ISSUE TITLE
Unaccessible after crash

### ISSUE THREAD

**Issue by webdobe** [tobybatch/kimai2#128]
**Describe the bug**

The other day my server crashed...  When trying to start kimai back up... Everything starts up fine but nginx cannot get a solid healthcheck.

I get this that repeats:
[27/Jun/2020:01:48:17 +0000] 172.18.0.2 - - - _ to: 172.18.0.2:9000: GET / HTTP/1.1 302 upstream_response_time 0.515 msec 1593222497.428 request_time 0.515
[27/Jun/2020:01:48:17 +0000] 172.18.0.2 - - - _ to: 172.18.0.2:9000: GET /en/homepage HTTP/1.1 302 upstream_response_time 0.463 msec 1593222497.892 request_time 0.463
[27/Jun/2020:01:48:18 +0000] 172.18.0.2 - - - _ to: 172.18.0.2:9000: GET /en/login HTTP/1.1 200 upstream_response_time 0.602 msec 1593222498.496 request_time 0.603

So / redirects to /en/homepage which redirects to /en/login which all sounds

The php fpm logs:
1.9
Using Mysql DB
Wait for db connection ...
Connection established
first run - install kimai

Kimai installation running ...
==============================

 ! [NOTE] Database is existing and connection could be established              

                                                              
                    Application Migrations                    
                                                              

No migrations to execute.

 Rebuilding your cache, please be patient ...

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    

 // Warming up the cache for the dev environment with debug                     
 // true                                                                        

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/var/cache/dev/pools/MJNq1WPcHS/9/O/1nRTbsNBB-Fhxa9hsayw on line 1
01:48:05 CRITICAL  [php] Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) ["exception" => Symfony\Component\ErrorHandler\Error\OutOfMemoryError { …}]

In 1nRTbsNBB-Fhxa9hsayw line 1:
                                                                               
  Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate   
  32768 bytes)                                                                 
                                                                               

kimai:install [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

Kimai2 ready

Reloading configurations ...
============================

 [ERROR] File or directory "config" is not readable.

I am mounting to a volume.  Never saw these issues before.  I have deleted volumes and restarted... Error goes away till I restart but nothing can connect.  This is all the same configuration as it was when it worked... I am wondering if something in the database is causing this issue?  I have a bunch of time logged so I don't wanna ditch my database.

**To Reproduce**
Not sure...

**Desktop (please complete the following information):**
NAME="CentOS Linux"
VERSION="7 (Core)"
 - Docker version: [e.g. 19.03.2]
Docker version 18.09.6, build 481bc77156
 - Docker compose version: [e.g. 1.21.0]
docker-compose version 1.21.2, build a133471

**Command used to run the container**
 - [e.g. docker run -v ....]
docker-compose up -d

**Docker compose file (with passwords redacted)**
```yaml
version: '3.5'
services:
  nginx:
    container_name: kimai_nginx
    image: nginx:1.18
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://kimai_nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    container_name: kimai_fpm
    image: kimai/kimai2:fpm-alpine-1.9-prod
    environment:
      - APP_ENV=dev
      - DATABASE_URL=
      - APP_SECRET=
      - TRUSTED_PROXIES=127.0.0.1,localhost,kimai_nginx
      - TRUSTED_HOSTS=127.0.0.1,localhost,kimai_nginx
      #- ADMINMAIL=
      #- ADMINPASS=
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://kimai_nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    container_name: kimai_postfix
    image: catatnight/postfix:latest
    environment:
      maildomain: 
      smtp_user: 
    restart: unless-stopped
    restart: always

volumes:
  var:
  public:
```

**Additional context**
I am really not sure why it is doing what it is doing. I have tried getting information from logs but it is pretty grim.

**Comment by kevinpapst** [comment]
Not directly targeted advice to your case but more of a general hint/question.

Why are you running in `APP_ENV=dev`? `dev` uses much more memory than `prod`.
You could also check if php.ini in bash has unlimited memory:
`php -i|grep memory_limit` should give you `memory_limit => -1`

If the server crashed, you could also check if the database is corrupted with `SHOW TABLE STATUS FROM kimai2`

**Comment by webdobe** [comment]
I only switched to dev to see if it provided more logging info.  Switching it back does nothing.  Table status is fine.  I was on 1.8 so I did switch it to 1.9 to see if an upgrade would resolve the issue.  Which it ran the migrations fine and all that but still no dice.

**Comment by webdobe** [comment]
This concerns me:

Reloading configurations ...
============================

 [ERROR] File or directory "config" is not readable. 

But I don't know why config is not readable.  I am able to log into the container and that /opt/kamai/config is there readable... With everything set to the www-data user/group.

**Comment by webdobe** [comment]
When I log into the nginx container... All the user/groups are 82:82... Which means that nginx likely doesn't have access to the public directory.

**Comment by webdobe** [comment]
Changed on the nginx container and now the fpm reads xfs/xfs for user/group.  So it seems that maybe the user id's are out of sync?

**Comment by kevinpapst** [comment]
Sorry, but I am out, thats a case for someone who knows docker.

**Comment by tobybatch** [comment]
@webdobe Switching to dev in the prod image won't work.  The prod image does not have the dev extensions installed.

I'll have a check but we don't set a custom UID for the fpm user.

**Comment by tobybatch** [comment]
We don't switch UIDs anywhere but I do notice that you have a custom php, and fpm config.  Could I see those please? 

Also your nginx set up might help.

**Comment by webdobe** [comment]
Hi so the custom php and fpm config were just to turn on logging to see if I could get anything from that.  I turned them off.  I got it working again. I had some configuration that had to do with traefik.  Which does bring up the question.  What am I missing about setting a trusted proxy for traefik?

nginx docker-compose with traefik setting commented out.
```
version: '3.5'
services:
  nginx:
    container_name: kimai_nginx
    image: nginx:1.18
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - public:/opt/kimai/public
    restart: unless-stopped
 #   labels:
 #     - "traefik.backend=kimai_nginx"
 #     - "traefik.port=80"
 #     - "traefik.enable=true"
 #     - "traefik.frontend.rule=Host:custom.com"
 #     - "traefik.docker.network=traefik_net"
 #     - "traefik.frontend.entryPoints=http,https"
 #     - "traefik.frontend.passHostHeader=true"
    ports:
      - "8888:80"
    depends_on:
      - kimai
    networks:
      - traefik_net
    healthcheck:
      test:  wget --spider http://kimai_nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
```
nginx config
```
log_format upstreamlog '[$time_local] $remote_addr - $remote_user - $server_name to: $upstream_addr: $request $status upstream_response_time $upstream_response_time msec $msec request_time $request_time';

server {
    listen 80;
    index index.php;
    server_name _;
    root /opt/kimai/public;

    # cache static asset files
    location ~* \.(ico|css|js|gif|jpe?g|png)(\?[0-9]+)?$ {
        expires max;
        log_not_found off;
    }

    # for health checks
    location /health {
        access_log  /dev/stdout upstreamlog;
        return 200 'alive';
        add_header Content-Type text/plain;
    }

    location / {
        access_log  /dev/stdout upstreamlog;
        # try to serve file directly, fallback to index.php
        try_files $uri $uri/ /index.php$is_args$args;
    }
    
    location ~ ^/index\.php(/|$) {
	access_log  /dev/stdout upstreamlog;
        fastcgi_pass kimai_fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        # optionally set the value of the environment variables used in the application
        # fastcgi_param APP_ENV prod;
        # fastcgi_param APP_SECRET <app-secret-id>;
        # fastcgi_param DATABASE_URL "mysql://db_user:db_pass@host:3306/db_name";

        # When you are using symlinks to link the document root to the
        # current version of your application, you should pass the real
        # application path instead of the path to the symlink to PHP
        # FPM.
        # Otherwise, PHP's OPcache may not properly detect changes to
        # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
        # for more information).
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        # Prevents URIs that include the front controller. This will 404:
        # http://domain.tld/index.php/some-path
        # Remove the internal directive to allow URIs like this
        internal;
    }
}
```
