### ISSUE TITLE
[BUG] Unable to start kimai with docker-compose

### ISSUE THREAD

**Issue by zwarag** [tobybatch/kimai2#133]
**Describe the bug**
I am unable to run kimai in using docker-compose. My guess I'm misunderstanding something.
After I `docker-compose up -d`, I try to access kimai on `http://localhost:9000`.  
I expected port 9000 because I've found it here: [docker hub](https://hub.docker.com/layers/kimai/kimai2/fpm-alpine-1.8-prod/images/sha256-12eabc46583818cf1943b20ea1edd3f8456b2d71d7ebca276b74561cb664e6bd?context=explore)

Unfortunately I get no response.  
Looking at the logs I see the following message that might be a hint. I omitted some parts of the logs because it is just the standard migration things that would clutter this report:
```
kimai_1    | 1.8
kimai_1    | Using non mysql DB
kimai_1    | first run - install kimai
kimai_1    | 
kimai_1    | Kimai installation running ...
kimai_1    | ==============================
kimai_1    |
kimai_1    | Created database /opt/kimai/var/data/kimai.sqlite for connection named default
kimai_1    |
kimai_1    |                     Application Migrations
kimai_1    |
kimai_1    |
kimai_1    | Migrating up to 20200205115244 from 0
...
kimai_1    |   ------------------------
kimai_1    |
kimai_1    |   ++ finished in 1090.1ms
kimai_1    |   ++ used 18M memory
kimai_1    |   ++ 32 migrations executed
kimai_1    |   ++ 359 sql queries
kimai_1    |
kimai_1    |  Rebuilding your cache, please be patient ...
kimai_1    |
kimai_1    |  // Clearing the cache for the prod environment with debug
kimai_1    |  // false
kimai_1    |
kimai_1    |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
kimai_1    |
kimai_1    |
kimai_1    |  // Warming up the cache for the prod environment with debug
kimai_1    |  // false
kimai_1    |
kimai_1    |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   
kimai_1    |
kimai_1    |
kimai_1    |  [OK] Congratulations! Successfully installed Kimai 2 version 1.8 (stable)
kimai_1    |
kimai_1    | 
kimai_1    |  [OK] Success! Created user: superadmin
kimai_1    |
kimai_1    | Kimai2 ready
kimai_1    |
kimai_1    | Reloading configurations ...
kimai_1    | ============================
kimai_1    |
kimai_1    |  [ERROR] File or directory "config" is not readable.
kimai_1    |
kimai_1    | [18-Jul-2020 18:05:08] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
kimai_1    | [18-Jul-2020 18:05:08] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
kimai_1    | [18-Jul-2020 18:05:08] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
kimai_1    | [18-Jul-2020 18:05:08] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
kimai_1    | [18-Jul-2020 18:05:08] NOTICE: fpm is running, pid 1
kimai_1    | [18-Jul-2020 18:05:08] NOTICE: ready to handle connections
```

**To Reproduce**
Use the compose file below and start it with the command listed below.

**Desktop (please complete the following information):**
 - OS: Linux & Windows
 - Docker version: 19.03.8, build afacb8b
 - Docker compose version:  1.25.5, build 8a1c60f6

**Command used to run the container**
 - `docker-compose up -d`

**Docker compose file (with passwords redacted)**
I got it from here: https://hub.docker.com/r/kimai/kimai2  
All I did is remove the nginx container because I do not need it.

```yaml
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -pchangemeplease ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:fpm-alpine-1.8-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=localhost
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    ports: 
      - "9000:9000"
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix:latest
    environment:
      maildomain: kimai.local
      smtp_user: kimai:kimai
    restart: unless-stopped

volumes:
    var:
    public:
```

**Additional context**
I tried to run these commands to make sure that I do not have the permission problem listed on the docker hub page.
`docker-compose --user root exec CONTAINER_NAME chown -R www-data:www-data /opt/kimai/var`  
The error remains the same (and yes I did NOT remove the var volume and I also tried to do a "clean restart" of the kimai container)

Just to be clear, this might seem strange that I do not use the nginx but I'd actually deploy this on my docker swarm setup that uses traefik to do the reverse proxying, https, caching, and so on.    
I did not write that on top because I'm not ready to use it in docker swarm yet, because I'd need to get this working first 😅  
But I figured I include this into the issue just to give context as to why I'm approaching it like that.
