### ISSUE TITLE
[BUG] 403 Forbidden (nginx/1.19.2)

### ISSUE THREAD

**Issue by apiening** [tobybatch/kimai2#156]
**Describe the bug**
After deployment, the website responds with **403 Forbidden - nginx/1.19.2**.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create file **docker-compose.yml** (see below)
2. Save the folder **compose** from this repository in the working directory.
3. Change ownership of the folders **db** and **var** to **999** respective **82:82** to match the uids the containers are using.
4. Bring the containers up with `docker-compose up -d --build && docker-compose logs -f`
5. Point browser at http://<host-ip>:8091/

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Docker version: 19.03.8
 - Docker compose version: 1.24.1

**Command used to run the container**
 - docker-compose up -d --build && docker-compose logs -f

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p${MYSQL_ROOT_PASSWORD} ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    build: compose
    ports:
      - 8091:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:fpm-alpine-1.10.1-prod
    environment:
      - APP_ENV=prod
      - APP_SECRET=${APP_SECRET}
      - TRUSTED_PROXIES=*,nginx,localhost,127.0.0.1
      - TRUSTED_HOSTS=*,nginx,localhost,127.0.0.1
      - ADMINMAIL=${ADMINMAIL}
      - ADMINPASS=${ADMINPASS}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sqldb/${MYSQL_DATABASE}
    volumes:
      - ./public:/opt/kimai/public
      - ./var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
```

**Additional context**
I started with the **docker-compose.yml** example from this repo.
I noticed that:
- The **kimai** image was pretty old, I updated to **fpm-alpine-1.10.1-prod**
- The **environment** var **DATABASE_URL** was missing, I set it to: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sqldb/${MYSQL_DATABASE}

**Comment by jokay** [comment]
@apiening the output of `docker-compose logs -f` may be helpful.

**Comment by apiening** [comment]
Hi @x-jokay,

here is the output of `docker-compose logs -f`;

```log
Attaching to kimai2_nginx_1, kimai2_kimai_1, kimai2_sqldb_1
kimai_1  | 1.10.1
kimai_1  | Using Mysql DB
kimai_1  | Wait for db connection ...
nginx_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1  | 10-listen-on-ipv6-by-default.sh: error: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
sqldb_1  | 2020-09-08 14:41:22+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.31-1debian10 started.
sqldb_1  | 2020-09-08 14:41:22+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
sqldb_1  | 2020-09-08 14:41:22+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.31-1debian10 started.
sqldb_1  | 2020-09-08T14:41:23.132325Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
sqldb_1  | 2020-09-08T14:41:23.137261Z 0 [Note] mysqld (mysqld 5.7.31) starting as process 1 ...
sqldb_1  | 2020-09-08T14:41:23.143102Z 0 [Note] InnoDB: PUNCH HOLE support available
sqldb_1  | 2020-09-08T14:41:23.143139Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
sqldb_1  | 2020-09-08T14:41:23.143148Z 0 [Note] InnoDB: Uses event mutexes
sqldb_1  | 2020-09-08T14:41:23.143151Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
sqldb_1  | 2020-09-08T14:41:23.143157Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
sqldb_1  | 2020-09-08T14:41:23.143165Z 0 [Note] InnoDB: Using Linux native AIO
sqldb_1  | 2020-09-08T14:41:23.143320Z 0 [Note] InnoDB: Number of pools: 1
sqldb_1  | 2020-09-08T14:41:23.143397Z 0 [Note] InnoDB: Using CPU crc32 instructions
sqldb_1  | 2020-09-08T14:41:23.144695Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
sqldb_1  | 2020-09-08T14:41:23.150187Z 0 [Note] InnoDB: Completed initialization of buffer pool
sqldb_1  | 2020-09-08T14:41:23.152146Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
sqldb_1  | 2020-09-08T14:41:23.178773Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
sqldb_1  | 2020-09-08T14:41:23.298013Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
sqldb_1  | 2020-09-08T14:41:23.298428Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
sqldb_1  | 2020-09-08T14:41:23.357305Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
sqldb_1  | 2020-09-08T14:41:23.360787Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
sqldb_1  | 2020-09-08T14:41:23.360818Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
sqldb_1  | 2020-09-08T14:41:23.361505Z 0 [Note] InnoDB: Waiting for purge to start
sqldb_1  | 2020-09-08T14:41:23.412426Z 0 [Note] InnoDB: 5.7.31 started; log sequence number 15438928
sqldb_1  | 2020-09-08T14:41:23.413193Z 0 [Note] Plugin 'FEDERATED' is disabled.
sqldb_1  | 2020-09-08T14:41:23.414530Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
sqldb_1  | 2020-09-08T14:41:23.443131Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
sqldb_1  | 2020-09-08T14:41:23.443160Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
sqldb_1  | 2020-09-08T14:41:23.448652Z 0 [Warning] CA certificate ca.pem is self signed.
sqldb_1  | 2020-09-08T14:41:23.449405Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
sqldb_1  | 2020-09-08T14:41:23.453271Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
sqldb_1  | 2020-09-08T14:41:23.453328Z 0 [Note] IPv6 is available.
sqldb_1  | 2020-09-08T14:41:23.453344Z 0 [Note]   - '::' resolves to '::';
sqldb_1  | 2020-09-08T14:41:23.453364Z 0 [Note] Server socket created on IP: '::'.
sqldb_1  | 2020-09-08T14:41:23.456191Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
sqldb_1  | 2020-09-08T14:41:23.486991Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200908 14:41:23
sqldb_1  | 2020-09-08T14:41:23.650711Z 0 [Note] Event Scheduler: Loaded 0 events
sqldb_1  | 2020-09-08T14:41:23.651032Z 0 [Note] mysqld: ready for connections.
sqldb_1  | Version: '5.7.31'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
kimai_1  | Connection established
kimai_1  | first run - install kimai
kimai_1  |
kimai_1  | Kimai installation running ...
kimai_1  | ==============================
kimai_1  |
kimai_1  | Database `kimai` for connection named default already exists. Skipped.
kimai_1  |
kimai_1  |                     Application Migrations
kimai_1  |
kimai_1  |
kimai_1  | No migrations to execute.
kimai_1  |
kimai_1  |  Rebuilding your cache, please be patient ...
kimai_1  |
kimai_1  |  // Clearing the cache for the prod environment with debug
kimai_1  |  // false
kimai_1  |
nginx_1  | 2020/09/08 14:41:42 [error] 20#20: *1 directory index of "/opt/kimai/public/" is forbidden, client: 172.21.0.3, server: php-docker.local, request: "GET / HTTP/1.1", host: "nginx"
nginx_1  | 172.21.0.3 - - [08/Sep/2020:14:41:42 +0000] "GET / HTTP/1.1" 403 153 "-" "Wget" "-"
nginx_1  | 172.21.0.4 - - [08/Sep/2020:14:41:42 +0000] "GET /health HTTP/1.1" 200 5 "-" "Wget" "-"
kimai_1  |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
kimai_1  |
kimai_1  |
kimai_1  |  // Warming up the cache for the prod environment with debug
kimai_1  |  // false
kimai_1  |
kimai_1  |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
kimai_1  |
kimai_1  |
kimai_1  |  [OK] Congratulations! Successfully installed Kimai 2 version 1.10.1 (stable)
kimai_1  |
kimai_1  |
kimai_1  |  [ERROR] username (superadmin)
kimai_1  |              The username is already used.
kimai_1  |
kimai_1  |  [ERROR] email (admin@example.com)
kimai_1  |              The email is already used.
kimai_1  |
kimai_1  | Kimai2 ready
kimai_1  |
kimai_1  | Reloading configurations ...
kimai_1  | ============================
kimai_1  |
kimai_1  |  [ERROR] File or directory "config" is not readable.
kimai_1  |
kimai_1  | [08-Sep-2020 14:42:01] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
kimai_1  | [08-Sep-2020 14:42:01] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
kimai_1  | [08-Sep-2020 14:42:01] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
kimai_1  | [08-Sep-2020 14:42:01] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
kimai_1  | [08-Sep-2020 14:42:01] NOTICE: fpm is running, pid 1
kimai_1  | [08-Sep-2020 14:42:01] NOTICE: ready to handle connections
nginx_1  | 172.21.0.3 - - [08/Sep/2020:14:42:02 +0000] "GET / HTTP/1.1" 403 153 "-" "Wget" "-"
nginx_1  | 2020/09/08 14:42:02 [error] 20#20: *3 directory index of "/opt/kimai/public/" is forbidden, client: 172.21.0.3, server: php-docker.local, request: "GET / HTTP/1.1", host: "nginx"
nginx_1  | 172.21.0.4 - - [08/Sep/2020:14:42:03 +0000] "GET /health HTTP/1.1" 200 5 "-" "Wget" "-"
```

**Comment by jokay** [comment]
This one looks strange, especially the server `php-docker.local`.

```sh
nginx_1  | 2020/09/08 14:41:42 [error] 20#20: *1 directory index of "/opt/kimai/public/" is forbidden, client: 172.21.0.3, server: php-docker.local, request: "GET / HTTP/1.1", host: "nginx"
```

**Comment by kevinpapst** [comment]
What about 
```
nginx_1  | 10-listen-on-ipv6-by-default.sh: error: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
```
and 
```
[ERROR] File or directory "config" is not readable.
```
Seems there is a general permission issue?

**Comment by apiening** [comment]
@x-jokay yes, that's indicating the cause of this issue:
I noticed that the volume **public** is empty, even after successful deployment.

When I enter the **kimai** container with `docker-compose exec kimai /bin/bash` I can see that the application has been installed into `/opt/kimai/` but the subfolder `public` is empty.

When I remove the volume **public** from the nginx container and start it again, I can see the content is available inside the container. It looks like the volume is mounted over the folder `public`.
Having the folder `public` as a volume is required, because the containers **nginx** and **kimai** do share this folder.

Maybe there is some script missing or not working that copies the content for the `public` folder to it's destination when it is not empty?

**Comment by jokay** [comment]
```sh
nginx_1  | 10-listen-on-ipv6-by-default.sh: error: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
```

This can be ignored but has to do with the `:ro` for

```sh
volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
```

If we want the nginx container to overwrite the config, we may remove the `:ro` in the sample, but I can confirm it works with `:ro`.

**Comment by apiening** [comment]
> What about
> 
> ```
> nginx_1  | 10-listen-on-ipv6-by-default.sh: error: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
> ```
> Seems there is a general permission issue?

No that's on purpose. The file `nginx_site.conf` is mounted RO, see
```yaml
  nginx:
    build: compose
    ports:
      - 8091:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/opt/kimai/public:ro
```

**Comment by apiening** [comment]
Having the `nginx` config RO is also the case in the example `docker-compose.yml` and I don't think that `nginx` does change it's own config. At least it should not.

**Comment by kevinpapst** [comment]
Don't concentrate too much on the comments of a non docker user. I was just pointing out the other errors that showed in the logs.
I am more curious about `[ERROR] File or directory "config" is not readable.`.

**Comment by apiening** [comment]
I changed the volume for `public` to mount to `/opt/kimai/public2` temporarily like so:
```yaml
  kimai:
    image: kimai/kimai2:fpm-alpine-1.10.1-prod
    environment:
      - APP_ENV=prod
      - APP_SECRET=${APP_SECRET}
      - TRUSTED_PROXIES=*,nginx,localhost,127.0.0.1
      - TRUSTED_HOSTS=*,nginx,localhost,127.0.0.1
      - ADMINMAIL=${ADMINMAIL}
      - ADMINPASS=${ADMINPASS}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sqldb/${MYSQL_DATABASE}
    volumes:
      - ./public:/opt/kimai/public2
      - ./var:/opt/kimai/var
```
I then entered the container with `docker-compose exec kimai /bin/bash` and copied over the contents manually:
```bash
cd /opt/kimai/
cp -r public/* public2/
```
I then reverted the change (so that `public` mounts to `/opt/kimai/public` as it is supposed to do) and rebuilt the container.
Now it works, the frontend is reachable and I can log in to kimai.

However, this needs to be addressed. Not only is this a undocumented step to setup the environment that should not be required, this would also break any updates: When the `kimai` image is replaced with a newer one, the contents of the `public` folder then needs to be copied over manually, again.

Has this worked previously? If so, there needs to be something broken with the startup script I guess.
