### ISSUE TITLE
How do I add configurations which have to be placed in the local configs (local.yaml)?

### ISSUE THREAD

**Issue by rschaerer** [tobybatch/kimai2#16]
:information_source: The kimai [documentation](https://www.kimai.org/documentation/configurations.html#config-files) says that configurations which can't be done by env vars should be placed in the file `config/packages/local.yaml`.

:question: How do I add such configurations to this docker installation?

:eye: Example `config/packages/local.yaml` from the [docs](https://www.kimai.org/documentation/configurations.html#overwriting-local-configs-localyaml):

> An example config/packages/local.yaml file might look like this:
> ````
> kimai:
>    timesheet:
>        rounding:
>            default:
>                begin: 15
>                end: 15
> admin_lte:
>    options:
>        default_avatar: build/apple-touch-icon.png
>
> ````

**Comment by tobybatch** [comment]
@rschaerer You will need to mount that file when you start the container.  From memory it will look something like this:

    docker run --name kimai2  .. etc etc.. -v /opt/kimai-docker/local.yaml:/opt/kimai/config/packages/local.yaml tobybatch/kimai2:prod

**Comment by kevinpapst** [comment]
Added to the documentation:
https://www.kimai.org/documentation/docker.html

**Comment by whoisbarry** [comment]
✔️  I mounted my **local.yaml** file to `/opt/kimai/config/packages/local.yaml` with the following code.

```
kimai:

# --------------------------------------------------------------------------------
# AUTHENTICATION
# --------------------------------------------------------------------------------
    user:
        registration: false
        password_reset: true
# --------------------------------------------------------------------------------
```

:x: Unfortunately I am still able to register new users via the web interface.
:wrench: The settings don't show any hint to disable user registration either.

❓ How can I disable that?
