### ISSUE TITLE
[BUG] fpm-alpine-master-prod image listening only on ipv6?

### ISSUE THREAD

**Issue by limitedAtonement** [tobybatch/kimai2#170]
**Describe the bug**
It looks like the container is listening on ports 127.0.0.11:34435, 127.0.0.11:59220, and :::9000. The result is that when I set up a reverse proxy to the kimai container using

```
<VirtualHost *:443>
    ServerName time.example.org
    ProxyPass "/" "http://kimai:9000/"
    ProxyPreserveHost On
...
</VirtualHost>
```

Httpd says, "Connection reset by peer ... error reading status line from remote server kimai:9000"

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a docker stack with two services: httpd and kimai/kimai2:fpm-alpine-master-prod
2. Use the virtualhost definition above
3. Use a web browser to go to the appropriate URL
4. The browser shows 502 Proxy Error, the HTTPD logs are as mentioned above, and kimai logs show nothing.

**Environment:**
 - OS: Arch Linux
 - Docker version: 19.03.11-ce build 42e35e61f3
 - Docker compose version: I'm using docker stack, not docker-compose.

**Command used to run the container**
 - `docker stack deploy -c swarm.yml`

**Docker compose file (with passwords redacted)**

```yaml
version: '3.6'
services:
  manager:
    image: manager # an image created from httpd
    ....
  kimai:
    image: kimai/kimai2:fpm-alpine-master-prod
    expose:
      - 9000
    volumes:
      - ../kimai/kimai.sqlite:/opt/kimai/var/data/kimai.sqlite
```

**Additional context**
Logs from Kimai look good. It mentions running 39 migrations using 392 sql queries, but there is an error:

`[ERROR] File or directory "config" is not readable`

I'm not sure where `config` is supposed to be, so I'm not sure how to address this issue, but perhaps whatever this `config` is would offer a way to configure the listening interface to be `0.0.0.0` on port 80 instead of :: on port 9000?
