### ISSUE TITLE
[BUG] Connection to DB failed on startup

### ISSUE THREAD

**Issue by yayitazale** [tobybatch/kimai2#172]
Updated de MYSQL docker to latest and now I get this erro on the kimai docker log after host reboot:

`php -r "new PDO(\"mysql:host=$DB_HOST;dbname=$DB_BASE\", \"$DB_USER\", \"$DB_PASS\");" &> /dev/null
`

This is my compose:
```
version: '3.5'
services:
  mydb:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped

  kimai:
    image: kimai/kimai2:apache-debian-master-prod
    environment:
      - APP_ENV=prod
      #- TRUSTED_HOSTS=*****
      # These are added to override the the DB URL from env when checking the DB status during start up.
      - DATABASE_URL=mysql://user:password@mydb/kimai
    depends_on:
      - mydb
   restart: unless-stopped
     ports:
      - 80:8001

volumes:
  mysql:
```
