### ISSUE TITLE
[BUG] Kimai2 not starting

### ISSUE THREAD

**Issue by blurry-code** [tobybatch/kimai2#195]
**Describe the bug**
When I try to start the docker container on my server I get the following:
```
Argument 1 passed to Twig\Environment::getTemplateClass() must be of the type string, 
null given, called in /opt/kimai/vendor/twig/twig/src/Environment.php on line 309
```

**To Reproduce**
I just used the initial `docker run`. Also tried a very basic docker-compose file for convenience.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Docker version: 19.03.13
 - Docker compose version: 1.17.1

**Command used to run the container**
 - `docker run --rm -ti -p 8072:8001 --name kimai2 kimai/kimai2:latest-dev`

**Docker compose file (with passwords redacted)**
```yaml
version: "3"
services:
  kimai:
    container_name: kimai2
    user: "www-data:www-data"
    image: kimai/kimai2:latest-dev
    ports:
      - "8072:8001"
```

**Additional context**
I tested it on my local machine and everything works fine.
