### ISSUE TITLE
[BUG] 404 error while requesting main page

### ISSUE THREAD

**Issue by bioinfornatics** [tobybatch/kimai2#200]
Dear,
I tried to use your docker image with mysql. But they are nothing on the main page I got a 404 error

Below my config. Thanks for your help

```yaml
version: '3.3'

networks:
  internal-nw:
    internal: true
  outside-nw:

services:
    database:
        image: mysql:8
        container_name: kimai2_mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: something
            MYSQL_DATABASE: kimai
            MYSQL_USER: a_user
            MYSQL_PASSWORD: something
        ports: 
            - '3306:3306'
        volumes:
            - database-data:/var/lib/mysql
        networks:
             - outside-nw
             - internal-nw
        restart: unless-stopped
        
    kimai:
        image: kimai/kimai2
        container_name: kimai2
        environment:
            DB_TYPE: mysql
            DB_TYPE: a_user
            DB_PASS: something
            DB_HOST: '%'
            DB_PORT: 3306
            DB_BASE: kimai
            ADMINPASS: something
            ADMINMAIL: foo@gmail.com
        ports: 
            - '8001:8001'
        depends_on:
          - database
        networks:
            - internal-nw
        restart: unless-stopped

volumes:
  database-data:
```

**Comment by tobybatch** [comment]
Hi,

Not your fault.  The default docker image runs with with php FPM so it needs a server in front of it for static assets.

To evaluate the image the simplest thing is to use the apache debian version, just change the line `image: kimai/kimai2` to `kimai/kimai2:latest-dev`

See here for a list of images: https://hub.docker.com/repository/docker/kimai/kimai2/tags?page=1&ordering=last_updated&name=apache

For production sites we recommend the FPM image, see here: https://github.com/tobybatch/kimai2/blob/main/docs/docker-compose.md#docker-compose

**Comment by bioinfornatics** [comment]
Thanks a lot @tobybatch . I will take a took

**Comment by bioinfornatics** [comment]
Thanks @tobybatch with your help I got it.
Below the `docker-compose.yml` file used:

```
version: '3.3'

networks:
  internal-nw:
    internal: true
  outside-nw:

services:
    database:
        image: mysql:8
        container_name: kimai2_mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: passwordtochange
            MYSQL_DATABASE: kimai
            MYSQL_USER: a_user
            MYSQL_PASSWORD: passwordtochange
        ports: 
            - '6306:3306'
        volumes:
            - kimai_database-data:/var/lib/mysql
        networks:
             - outside-nw
             - internal-nw
        restart: unless-stopped
        
    kimai:
        image: kimai/kimai2:fpm-alpine-1.10.2-prod
        container_name: kimai2
        environment:
            APP_ENV: prod
            TRUSTED_HOSTS: localhost,nginx,${HOSTNAME}
            DB_TYPE: mysql
            DB_TYPE: a_user
            DB_PASS: passwordtochange
            DB_HOST: '%'
            DB_PORT: 6306
            DB_BASE: kimai
            ADMINPASS: passwordtochange
            ADMINMAIL: someone@gmail.com
        depends_on:
          - database
        networks:
            - internal-nw
        volumes:
            - kimai-root:/opt/kimai
            - kimai_public-data:/opt/kimai/public
        restart: unless-stopped
    
    server:
        image: nginx:1.19
        container_name: kimai2_nginx
        ports:
          - '8001:80'
          - '9000:9000'
        depends_on:
          - kimai
        volumes:
          - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
          - kimai_public-data:/opt/kimai/public:ro
          - kimai-root:/opt/kimai
        networks:
            - outside-nw
            - internal-nw
        restart: unless-stopped

    postfix:
        container_name: kimai2_postfix
        image: catatnight/postfix:latest
        environment:
            maildomain: kimai.local
            smtp_user: kimai:kimai
        restart: unless-stopped


volumes:
  kimai_database-data:
  kimai-root:
  kimai_public-data:
```
