### ISSUE TITLE
Docker image latest-prod runs "first run - install kimai" everytime the container starts

### ISSUE THREAD

**Issue by wadedugas** [tobybatch/kimai2#220]
Hi,

I created a docker compose file to use the Kimai docker image kimai/kimai2:latest-prod. How do I stop the kimai container from initializing Kimai every time the container starts?

Of course, this is a bit problematic for a production instance as it clears out all data on every restart ;-)

Here is the kimai service from my docker-copose.yml:
```
  kimai:
    image: kimai/kimai2:latest-prod
    container_name: ${KIMAI_CONTAINER_NAME}
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=127.0.0.1,localhost,nginx,${HOSTNAME}
      - ADMINMAIL=${ADMINMAIL}
      - ADMINPASS=${ADMINPASS}
      - DB_TYPE=mysql
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb/kimaidb
      - MAILER_URL=${MAILER_URL}
      - MAILER_FROM=${MAILER_FROM}
    volumes:
      - public:/opt/kimai/public # << You must use a named volume, see note below
      - var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
```

Thanks for your help!
