### ISSUE TITLE
Unable to get database tables information in docker container

### ISSUE THREAD

**Issue by JustTheSame** [tobybatch/kimai2#229]
I use `docker-compose.yml` start my kimai application.
```
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -pchangemeplease ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    build: compose
    ports:
      - 80:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - kimai
    volumes:
      - public:/opt/kimai/public
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:fpm-alpine-1.5-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=localhost
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    restart: unless-stopped
    restart: always

volumes:
    var:
    public:
```
RUN SUCCESS!

```
[root@kimai ~]# docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                  PORTS                 NAMES
a17152aba035        kimai2-master_nginx                "nginx -g 'daemon of…"   13 months ago       Up 2 months (healthy)   0.0.0.0:80->80/tcp    kimai2-master_nginx_1
611a8e1bbf4d        mysql:5.7                          "docker-entrypoint.s…"   13 months ago       Up 4 months (healthy)   3306/tcp, 33060/tcp   kimai2-master_sqldb_1
ac37ad31e6f4        catatnight/postfix                 "/bin/sh -c '/opt/in…"   13 months ago       Up 4 months                                   kimai2-master_postfix_1
a20f6058ee6e        kimai/kimai2:fpm-alpine-1.5-prod   "/bin/sh -c /startup…"   13 months ago       Up 4 months (healthy)   9000/tcp              kimai2-master_kimai_1
```

I want see my database tables in my container, but it's empty.

```
[root@kimai kimai2-master]# docker exec -it kimai2-master_sqldb_1 /bin/bash

root@611a8e1bbf4d:/# mysql -u kimaiuser -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 594069
Server version: 5.7.29 MySQL Community Server (GPL)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use kimai
Database changed
mysql> show tables;
Empty set (0.00 sec)
```
The kimai application is working normally. Can you help me to solve it？

Thanks~
