### ISSUE TITLE
Kimai application loses connection to database when upgrading from fpm-alpine-1.13 to fpm-1.14-prod

### ISSUE THREAD

**Issue by urinal-cake** [tobybatch/kimai2#237]
This may not be a bug, as much as it could potentially be a problem with my setup. After modifying my docker-compose image from:
```
image: kimai/kimai2:fpm-alpine-1.13-prod
```
to
```
image: kimai/kimai2:fpm-1.14-prod
```

The Kimai2 container logs show the following:
```
kimai_1    | Unkown database type, cannot proceed.  Expected one of: mysql, sqlite. Received: []
```

Initially, I noticed that when compared to the docker-compose example located [here](https://github.com/tobybatch/kimai2/blob/main/docker-compose.yml), that I was missing this line:
```
- DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai`
```
I added the line with the username, password, host and database set properly and began receiving this error:
```
Testing DB:** new \PDO(mysql:host=sqldb;dbname=kimai;port=3399, <user>, <password>, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*SQLSTATE[HY000] [2002] Connection refused (?)Checking DB: 10
```
I have tested connectivity to the MySQL DB host (has not had `container_name` set) called `sqldb` and ensured that my username and password are correct (<user> $MYSQL_USER, and <password> instead of $MYSQL_PASSWORD) I also tried to swap with the password declared in the db envvars for MYSQL_ROOT_PASSWORD

When the wrong host address was provided, I correctly received:
```
Testing DB:** new \PDO(mysql:host=<wrongHost>;dbname=kimai;port=3399, <user>, <password>, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve (?)Checking DB: 10
```

When the wrong database name was provided, I received the same Connection refused error as above.

This leads me to believe that my username and password are not actually set correctly, but logging in with $MYSQL_USER and $MYSQL_PASSWORD within the sqldb container shows the following:
```
urinal-cake@kimai:/opt/kimai$ sudo docker exec -it kimai_sqldb_1 /bin/bash
root@2264223e9f90:/# mysql -u $MYSQL_USER -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 255
Server version: 5.7.34 MySQL Community Server (GPL)

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| kimai              |
+--------------------+
2 rows in set (0.00 sec)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Docker version: Docker version 19.03.8, build afacb8b7f0
 - Docker compose version: docker-compose version 1.17.1, build unknown

**Command used to run the container**
 - sudo docker-compose up -d

**Docker compose file (with passwords redacted)**

```yaml
version: '3.4'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=redactedUser
      - MYSQL_PASSWORD=redactedPassword
      - MYSQL_ROOT_PASSWORD=redactedRootPassword
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -predactedRootPassword ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    build: compose
    ports:
      - 8001:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - kimai
    volumes:
      - public:/opt/kimai/public
    healthcheck:
      test:  wget --spider https://timesheet.punyhuman.com/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:fpm-alpine-1.13-prod
    #image: kimai/kimai2:fpm-1.14-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=timesheet.punyhuman.com,127.0.0.1,timesheet.hotdog.punyhuman.com,local,localhost
      - TRUSTED_PROXIES=10.20.10.118
        #- DATABASE_URL=mysql://redactedUser:redactedPassword@sqldb:3399/kimai
      - ADMINMAIL=ops@punyhuman.com
      - ADMINPASS=redactedKimaiAdminPassword
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
      - /opt/punykimai/plugins:/opt/kimai/var/plugins
      - /opt/punykimai/config/local.yaml:/opt/kimai/config/packages/local.yaml
    restart: unless-stopped
    healthcheck:
      test: wget --spider https://timesheet.punyhuman.com || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: punyhuman.com
      smtp_user: kimai:kimai
    restart: unless-stopped
    restart: always

volumes:
    var:
    public:
```
