### ISSUE TITLE
[BUG]  LDAP Group Mappings not working

### ISSUE THREAD

**Issue by PenguinzTech** [tobybatch/kimai2#253]
**Describe the bug**
I created a mapping based on docs for 3 groups in ldap I created for Role mapping, they are not applying. The user can login, but they do not receive the team lead, admin, or super admin roles.

**To Reproduce**
Steps to reproduce the behaviour:
Apply mapping based off config:
```
kimai:
    user:
        registration: false
        password_reset: false
    permissions:
        roles:
            ROLE_USER: ['!password_own_profile']
            ROLE_TEAMLEAD: ['!password_own_profile']
            ROLE_ADMIN: ['!password_own_profile']
    ldap:
        connection:
            host: redacted
            port: redacted
            username: redacted
            password: redacted
            bindRequiresDn: true
        user:
            baseDn: ou=users,dc=penguinzmedia,dc=group
        role:
            baseDn: ou=groups,dc=penguinzmedia,dc=group
            groups:
                - { ldap_value: pmg-admin, role: ROLE_TEAMLEAD }
                - { ldap_value: time-admin, role: ROLE_ADMIN }
                - { ldap_value: infra-admin, role: ROLE_SUPER_ADMIN }
security:
    providers:
        chain_provider:
            chain:
                providers: [kimai_ldap]
    firewalls:
        secured_area:
            kimai_ldap: ~
```

**Desktop (please complete the following information):**
 - OS: 
 Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
 - Docker version: Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
 - Docker compose version: docker-compose version 1.25.0, build unknown

**Command used to run the container**
 - docker-compose up -d

**Docker compose file (with passwords redacted)**

``` 
version: '3.5'
services:
  kimaidb:
    image: mariadb   
    networks:
      - kimainet
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=redacted
      - MYSQL_DATABASE=kimai
    restart: always
    volumes:
      - kimaidb:/var/lib/mysql

  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    networks:
      - kimainet
    ports:
      - 8001:80
    volumes:
      - public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:fpm
    networks:
      - kimainet
    ports:
      - 9000:9000
    environment:
      - ADMINMAIL=redacted
      - ADMINPASS=redacted
      - DATABASE_URL=redacted
      - TRUSTED_HOSTS=redacted
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
      #- ./kimiadata:/etc/openldap/
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped

  #postfix:
  #  image: catatnight/postfix:latest
  #  environment:
  #    maildomain: neontribe.co.uk
  #    smtp_user: kimai:kimai
  #  restart: unless-stopped

volumes:
    var:
    public:
    kimaidb:
networks:
  kimainet:
```
^ looks like paste formatting messed up from my webcon, but validated and running docker instance.
**Additional context**
All other aspects of ldap seem to running, not sure here.

**Comment by tobybatch** [comment]
So.... This isn't really a docker (or a Kimai) issue, but instead an LDAP set up issue.We use LDAP at neontribe but I'm not an expert.

This is our set up (that does work):

```yaml
        role:
            baseDn: ou=groups,dc=XXXX,dc=XXXX
            filter: (&(objectClass=posixGroup))
            usernameAttribute: uid
            nameAttribute: cn
            userDnAttribute: memberUid
            groups:
                - { ldap_value: kimai-teamleader, role: ROLE_TEAMLEAD }
                - { ldap_value: kimai-admin, role: ROLE_ADMIN }
                - { ldap_value: kimai-superadmin, role: ROLE_SUPERADMIN }
```

Maybe you need to better target the LDAP search?
