### ISSUE TITLE
KimaiV2 as Docker container with email setup

### ISSUE THREAD

**Issue by lmigo** [tobybatch/kimai2#26]
Hi Toby, 

in my docker-compose.yml I've override the environment for MAILER_URL and MAILER_FROM but when I check the SwiftmailerBundle, there are still shown the default values.

`docker-compose.yml`

```
kimai:
  ...
  environment:
    ...
    - MAILER_URL=smtp://username%40domain.com:password@smtp.gmail.com:587?encryption=tls&auth_mode=login
    - MAILER_FROM=username%40domain.com
```

`docker exec kimai bin/console debug:config SwiftmailerBundle`

```
Current configuration for "SwiftmailerBundle"
=============================================

swiftmailer:
    default_mailer: default
    mailers:
        default:
            url: '%env(MAILER_URL)%'
            spool:
                type: memory
                path: '%kernel.cache_dir%/swiftmailer/spool'
                id: null
            transport: smtp
            command: '/usr/sbin/sendmail -bs'
            username: null
            password: null
            host: localhost
            port: null
            timeout: 30
            source_ip: null
            local_domain: null
            encryption: null
            auth_mode: null
            delivery_addresses: {  }
            logging: false
            delivery_whitelist: {  }
```

Should my overwritten environment be visible in this output?

Thanks,
Michael
