### ISSUE TITLE
Protocol error when marking invoice as paid over reverse proxy

### ISSUE THREAD

**Issue by praul** [tobybatch/kimai2#269]
**Describe the bug**
When marking an invoice as paid there is an error when using a reverse proxy

`app.3b90b56b.js:2 Mixed Content: The page at 'https://XXX.duckdns.org/de/invoice/show' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http:/XXX.duckdns.org/de/invoice/change-status/27/paid'. This request has been blocked; the content must be served over HTTPS.`

This error only occurs on marking invoices as paid. Everything else works fine. Since this feature changed recently, I assume it does not use the same method for communicating with backend as all other operations.

This error occurs on both caddy and traefik as reverse proxies.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the containers over the supplied docker-compose file plus labels for reverse proxy at the nginx-container '
2. Mark some invoice as paid.

**Desktop (please complete the following information):**
 - docker-ce 19.03.15
 - docker-compose version 1.27.4, build 40524192

**Command used to run the container**
 - docker-compose up -d

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:
  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - /docker/user/datas/kimai/mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - internal


  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    ports:
      - 8001:80
    volumes:
      - public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - caddy
      - internal
      #- traefik
    labels:
      caddy: XXXX.duckdns.org
      caddy.reverse_proxy.header_up_0: X-Forwarded-Proto {scheme}
      caddy.reverse_proxy.header_up_1: X-Forwarded-Host {host}
      caddy.reverse_proxy: '{{upstreams 80 http}}'


  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:fpm
    environment:
      - ADMINMAIL=XXXX
      - ADMINPASS=XXXX
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,XXX
    volumes:
      - public:/opt/kimai/public
      - /docker/user/datas/kimai/var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    networks:
      - internal

  postfix:
    image: catatnight/postfix:latest
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    restart: unless-stopped
    networks:
      - internal


volumes:
    public:

networks:
  internal:
    external: false
  caddy:
    external: true

```
