### ISSUE TITLE
[BUG] index.php returns 404 with fpm forwarding

### ISSUE THREAD

**Issue by DavyLandman** [tobybatch/kimai2#271]
**Describe the bug**
After setting up a docker-compose with fpm forwarding, the index.php returns a 404 from the kimai server side.

**To Reproduce**
Steps to reproduce the behaviour:

1. open main url
2. get 404
3. access log from nginx:
```
main-proxy_1   | 2021/06/23 14:01:11 [error] 22#22: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 141.101.105.150, server: kimai.swat.engineering, request: "GET /index.html HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "kimai.swat.engineering"
```

4. log from kimai:

```
kimai_1        | 172.18.0.5 -  23/Jun/2021:15:01:11 +0100 "GET /index.php" 404
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian 10
 - Docker version: [e.g. 19.03.2]  20.10.7
 - Docker compose version: [e.g. 1.21.0] 1.27.0

**Docker compose file (with passwords redacted)**

```yaml
  main-proxy:
    restart: always
    image: nginx:mainline
    volumes:
      - /srv/swat/assets/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/swat/assets/config/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /srv/swat/assets/config/nginx/includes/:/etc/nginx/includes/:ro
      - public:/srv/kimai:ro
    ports:
      - "80:80"
      - "443:443"
  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:fpm-1.14.3-prod
    environment:
      - ADMINMAIL=X
      - ADMINPASS=X
      - DATABASE_URL=mysql://kimaiuser:XXX@sqldb/kimai
      - TRUSTED_HOSTS=nginx,localhost,main-proxy,127.0.0.1
    volumes:
      - public:/opt/kimai/public
      - /srv/swat/data/kimai/var:/opt/kimai/var
      - /srv/swat/data/kimai/data:/var/kimai/data
      - /srv/swat/assets/config/kimai.yaml:/opt/kimai/config/packages/local.yaml
    restart: unless-stopped
volumes:
  public:

```` 

**Additional context**

Config of the nginx vhost for kimai:

```
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;

	server_name kimai.swat.engineering;
	include /etc/nginx/includes/ssl.conf;
	access_log stderr;

	index index.php;
	root /srv/kimai;

	location ~* \.(ico|css|js|gif|jpe?g|png)(\?[0-9]+)?$ {
		expires max;
		log_not_found off;
	}


	location / {
		try_files $uri $uri/ /index.php$is_args$args;
	}

	location ~ ^/index\.php(/|$) {
		fastcgi_pass kimai:9000;
		fastcgi_split_path_info ^(.+\.php)(/.*)$;
		include fastcgi_params;

		fastcgi_param APP_ENV prod;
		fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
		fastcgi_param DOCUMENT_ROOT $realpath_root;
		internal;
	}

}
```

kimai log:

```
kimai_1        |
kimai_1        | Using Mysql DB
kimai_1        | Wait for db connection ...
kimai_1        | Testing DB:** new \PDO(mysql:host=sqldb;dbname=kimai;port=3306, kimaiuser, XXXX, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection
 established
kimai_1        |
kimai_1        | Kimai installation running ...
kimai_1        | ==============================
kimai_1        |
kimai_1        | Database `kimai` for connection named default already exists. Skipped.
kimai_1        |
kimai_1        |                     Application Migrations
kimai_1        |
kimai_1        |
kimai_1        | No migrations to execute.
kimai_1        |
kimai_1        |  Rebuilding your cache, please be patient ...
kimai_1        |
kimai_1        |  // Clearing the cache for the prod environment with debug
kimai_1        |  // false
kimai_1        |
kimai_1        |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
kimai_1        |
kimai_1        |
kimai_1        |  // Warming up the cache for the prod environment with debug
kimai_1        |  // false
kimai_1        |
kimai_1        |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
kimai_1        |
kimai_1        |
kimai_1        |  [OK] Congratulations! Successfully installed Kimai version 1.14.1
kimai_1        |
kimai_1        |
kimai_1        | Kimai updates running ...
kimai_1        | =========================
kimai_1        |
kimai_1        |
kimai_1        |                     Application Migrations
kimai_1        |
kimai_1        |
kimai_1        | No migrations to execute.
kimai_1        |
kimai_1        |  Rebuilding your cache, please be patient ...
kimai_1        |
kimai_1        |  // Clearing the cache for the prod environment with debug
kimai_1        |  // false
kimai_1        |
kimai_1        |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
kimai_1        |
kimai_1        |
kimai_1        |  // Warming up the cache for the prod environment with debug
kimai_1        |  // false
kimai_1        |
kimai_1        |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
kimai_1        |
kimai_1        |
kimai_1        |  [OK] Congratulations! Successfully updated Kimai to version 1.14.1
kimai_1        |
kimai_1        |
kimai_1        |  [ERROR] username (superadmin)
kimai_1        |              The username is already used.
kimai_1        |
kimai_1        |  [ERROR] email (davy.landman@swat.engineering)
kimai_1        |              The email is already used.
kimai_1        |
kimai_1        | Kimai2 ready
kimai_1        |
kimai_1        | Reloading configurations ...
kimai_1        | ============================
kimai_1        |
kimai_1        |
kimai_1        |  [OK] All 44 YAML files contain valid syntax.
kimai_1        |
kimai_1        |
kimai_1        |
kimai_1        |  [OK] All 404 XLIFF files contain valid syntax.
kimai_1        |
kimai_1        |
kimai_1        |  Rebuilding your cache, please be patient ...
kimai_1        |
kimai_1        |  // Clearing the cache for the prod environment with debug
kimai_1        |  // false
kimai_1        |
kimai_1        |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
kimai_1        |
kimai_1        |
kimai_1        |  // Warming up the cache for the prod environment with debug
kimai_1        |  // false
kimai_1        |
kimai_1        |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
kimai_1        |
kimai_1        |
kimai_1        |  [OK] Kimai config was reloaded
kimai_1        |
kimai_1        | [23-Jun-2021 15:01:09] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
kimai_1        | [23-Jun-2021 15:01:09] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
kimai_1        | [23-Jun-2021 15:01:09] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
kimai_1        | [23-Jun-2021 15:01:09] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
kimai_1        | [23-Jun-2021 15:01:09] NOTICE: fpm is running, pid 1
kimai_1        | [23-Jun-2021 15:01:09] NOTICE: ready to handle connections
```
