### ISSUE TITLE
[BUG] Invoice with payment date not saved - Error.

### ISSUE THREAD

**Issue by jamescraig-engineer** [tobybatch/kimai2#272]
**Describe the bug**
Set a payment date for a 'pending' invoice. Get error when trying to save.

**To Reproduce**
Mark any invoice to "PAID"

**Desktop (please complete the following information):**
 - OS: **Ubuntu**
 - Docker version: **19.03.13, build 4484c46d9d**
 - Docker compose version: **1.27.4, build 4052419**

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    container_name: kimai2_db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --default-storage-engine innodb
    ports:
      - 3308:3306
    volumes:
      - kimai2_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache
    container_name: kimai2_web
    ports:
      - 7777:8001
    volumes:
      - ./Invoices:/opt/kimai/var/data/invoices
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS}
    restart: unless-stopped

volumes:
    kimai2_data:
```
![kimai_paid_not_saved](https://user-images.githubusercontent.com/57005564/123832616-6eaba400-d8fd-11eb-9b1b-f966604428c6.jpg)

**Additional Information**
This also happens with invoices that were created in the past (before payment date was introduced). Nothing in the log. infact, by default, the docker Kimai has "Missing logfile" created it manually (touch var/log/prod.log) but nothing is logged there on this error, so I'm looking for some help on this. 

Kimai version: 1.14.1

**Docker Images:**
kimai/kimai2                        apache           96e317749942        5 weeks ago         698MB
mysql                                  5.7                 09361feeb475          6 days ago           447MB
