### ISSUE TITLE
[BUG] Issue with the Docker Compose Deployment.

### ISSUE THREAD

**Issue by liferelay** [tobybatch/kimai2#273]
When using the Compose Yaml the Nginx container will not stay up and I often receive the following errors.

nginx: [emerg] host not found in upstream "kimai" in /etc/nginx/conf.d/default.conf:24

**Comment by tobybatch** [comment]
docker-compose.yml please.

The issue is not with the kimai image but the container set up.

**Comment by liferelay** [comment]
version: '3.3'
services:
  kimai:
    image: kimai/kimai2:fpm
    environment:
      ADMINMAIL: admin@kimai.local
      ADMINPASS: changemeplease
      DATABASE_URL: mysql://kimaiuser:kimaipassword@sqldb/kimai
      TRUSTED_HOSTS: nginx,localhost,127.0.0.1
    volumes:
     - datapublic:/opt/kimai/public
    networks:
     - default
    logging:
      driver: json-file
  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy:latest
    healthcheck:
      test:
       - CMD-SHELL
       - wget --spider http://nginx/health || exit 1
      interval: 20s
      timeout: 10s
      retries: 3
    ports:
     - 8001:80
    volumes:
     - datapublic:/opt/kimai/public:ro
    networks:
     - default
    logging:
      driver: json-file
  postfix:
    image: catatnight/postfix:latest
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    networks:
     - default
    logging:
      driver: json-file
  sqldb:
    image: mysql:5.7
    command:
     - --default-storage-engine
     - innodb
    healthcheck:
      test:
       - CMD-SHELL
       - mysqladmin -p$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      timeout: 10s
      retries: 3
    environment:
      MYSQL_DATABASE: kimai
      MYSQL_PASSWORD: kimaipassword
      MYSQL_ROOT_PASSWORD: changemeplease
      MYSQL_USER: kimaiuser
    volumes:
     - mysql:/var/lib/mysql
    networks:
     - default
    logging:
      driver: json-file
networks:
  default:
    driver: overlay

**Comment by liferelay** [comment]
[kimaiv2.txt](https://github.com/tobybatch/kimai2/files/6742846/kimaiv2.txt)

**Comment by tobybatch** [comment]
And can I see the log output please? Especially where nginx restarts.

**Comment by tobybatch** [comment]
and your docker-compose.yml is missing the volumes key

**Comment by liferelay** [comment]
The Volume Key is not there because i'm actually binding them to a file path, but I removed them to obscure the actual location.

**Comment by liferelay** [comment]
Full Log output is:
 2021/06/30 17:34:14 [emerg] 1#1: host not found in upstream "kimai" in /etc/nginx/conf.d/default.conf:24
 nginx: [emerg] host not found in upstream "kimai" in /etc/nginx/conf.d/default.conf:24

**Comment by tobybatch** [comment]
Do pages ever serve from the kimai instance? I notice you are using a custom network and wondered why?

The error message point to the nginx container unable to resolve the name kimai into an ip address. You could try shelling onto the nginx container and checking.


These commands should work,  I've not tested them:

```
docker-compose exec nginx sh
```

and run 

```
nslookup kimai
ping kimai
```

**Comment by tobybatch** [comment]
And which OS/versions are you on. In fact if you'd fill in the info we asked for in the bug template that would really help.

[New bug ticket](https://github.com/tobybatch/kimai2/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D+)

**Comment by philipp65** [comment]
`/etc/nginx/conf.d/default.conf` shows that `kimai` is hardcoded. 

For me the solution was either renaming the container to `kimai` or custom mounting my own `default.conf`.

**Comment by chernesk** [comment]
@philipp65 Could you please detail what you did to get this working. I'd love to not have to reinvent the wheel. Can you post your docker-compose.yml in here or the steps that you went through?

Thank you!

**Comment by NK0D1NG** [comment]
Sorry for reopening this but I experience the exact same problem using the docker-compose file with Docker Swarm:
`nginx: [emerg] host not found in upstream "kimai" in /etc/nginx/conf.d/default.conf:24`

I already sh'd to the running container and did a ping and nslookup for kimai which is working fine. The kimai service is responding correctly and is reachable. Does anyone know what the problem is?

**Comment by tobybatch** [comment]
This isn't an issue with the container but the config. Your kimai instance does not have a the name `kimai` inside your cluster si the nginx reverse proxy cannot find it.

If this related to #352 then you need to check your swarm config. I don't use swarm so I can't directly help.

**Comment by philipp65** [comment]
> @philipp65 Could you please detail what you did to get this working. I'd love to not have to reinvent the wheel. Can you post your docker-compose.yml in here or the steps that you went through?
> 
> Thank you!

Sorry for the late response. Sure. @tobybatch basically pointed it out already.
**Problem**
I just ran into this issue, because I'm using a different `container_name` than `kimai` for the image `kimai/kimai2:fpm`. 
**Reason**
Because of this, `tobybatch/nginx-fpm-reverse-proxy` couldn't find the `kimai/kimai2:fpm` instance.
**Solution 1**
using the hostname which the reverse proxy is looking for
```yaml
  kimai:
    image: kimai/kimai2:fpm
    container_name: kimai
   ...
```
**Solution 2**
mounting a modified `default.conf` with a custom hostname inside the reverse proxy container
```yaml
  kimai_nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    volumes:
      - /somewhere/default.conf:/etc/nginx/conf.d/default.conf
   ...
```
with the line `fastcgi_pass your_container_name:9000;` modified to your needs.


**docker-compose.yml**
```
version: '3.8'

networks:
  traefik_time:
  time:

services:
  time:
    image: kimai/kimai2:fpm
    container_name: time
    restart: unless-stopped
    volumes:
      - /xx/yy/time/time/public:/opt/kimai/public
    networks:
      - time
    depends_on:
      - time_db
    env_file:
      - /xx/yy/time/time/.env

  time_nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    container_name: time_nginx
    volumes:
      - /xx/yy/time/time/public:/opt/kimai/public:ro
      - /xx/yy/time/time_nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - traefik_time
      - time
    depends_on:
      - time
    healthcheck:
      test:  wget --spider http://time_nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docker_traefik_time"
      - "traefik.http.routers.time.rule=Host(`time.xxx.tld`)"
      - "traefik.http.routers.time.tls=true"
      - "traefik.http.routers.time.tls.certResolver=default"
      - "traefik.http.services.time.loadbalancer.server.port=80"

  time_db:
    image: mysql:5.6
    container_name: time_db
    restart: always
    networks:
      - time
    volumes:
      - /xx/yy/time/time_db/mysql:/var/lib/mysql
    env_file:
      - /xx/yy/time/time_db/.env
    command: --default-storage-engine innodb
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
```
