### ISSUE TITLE
Issue with Kimai via Traefik

### ISSUE THREAD

**Issue by johabk** [tobybatch/kimai2#279]
Can someone cexplain, which stupid error I made in my compose file?
Kimai is working internally, but when I try to access it via through traefik, I get an Bad Gateway or an Gateway timeout.

docker-compose version 1.27.4, build 40524192

```yaml
version: '3.5'
services:

sqldb:
image: mysql:5.7
environment:
- MYSQL_DATABASE=kimai
- MYSQL_USER=kimaiuser
- MYSQL_PASSWORD=kimaipassword
- MYSQL_ROOT_PASSWORD=changemeplease
command: --default-storage-engine innodb
restart: unless-stopped
networks:
- kimai
nginx:
image: tobybatch/nginx-fpm-reverse-proxy
ports:
- "9190:80"
volumes:
- public:/opt/kimai/public:ro
restart: unless-stopped
depends_on:
- kimai
networks:
- kimaiproxy
- kimai
labels:
- "traefik.enable=true"
- "traefik.docker.network=proxy_default"
- "traefik.http.services.kimai-loadbalancer.loadbalancer.server.port=9190"
- "traefik.http.routers.kimai.rule=Host(time.mydomain.de) "
- "traefik.http.routers.kimai.entrypoints=websecure"
- "traefik.http.routers.kimai.tls.certresolver=myhttpchallenge"
- "traefik.http.routers.kimai-unsecure.rule=Host(time.mydomain.de)"
- "traefik.http.routers.kimai-unsecure.entrypoints=web"
- "traefik.http.routers.kimai-unsecure.middlewares=kimai-redis"
- "traefik.http.middlewares.kimai-redis.redirectscheme.scheme=https"
kimai: # This is the latest FPM image of kimai
image: kimai/kimai2:latest
environment:
- ADMINMAIL=admin@kimai.local
- ADMINPASS=changemeplease
- DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai
- TRUSTED_HOSTS=nginx,localhost,127.0.0.1,192.168.178.202,time.mydomain.de,172.29.24.8
networks:
- kimai
volumes:
- public:/opt/kimai/public
# - var:/opt/kimai/var
# - ./ldap.conf:/etc/openldap/ldap.conf:z
# - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
restart: unless-stopped

volumes:
var:
public:
networks:
kimaiproxy:
external:
name: proxy_default
kimai:
driver: bridge
```

**Comment by tobybatch** [comment]
Pretty much all of these errors end up being TRUSTED_HOST issues, https://tobybatch.github.io/kimai2/troubleshooting.html#500-server-errors

I don't use `traefik` so I can't really help. Do you hit the kimai instance at all? Can you attach the container logs?

**Comment by philipp65** [comment]
Here's my working traefik config for the reverse proxy:

`docker-compose.yml`
```
  time_nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    container_name: time_nginx
    volumes:
      - ./public:/opt/kimai/public:ro
    restart: unless-stopped
    networks:
      - traefik_time
      - time
    depends_on:
      - time
    healthcheck:
      test:  wget --spider http://time_nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docker_traefik_time"
      - "traefik.http.routers.time.rule=Host(`time.xxx.xx`)"
      - "traefik.http.routers.time.tls=true"
      - "traefik.http.routers.time.tls.certResolver=default"
      - "traefik.http.services.time.loadbalancer.server.port=80"
```

`.env`
```
...
TRUSTED_HOSTS=time_nginx,time.xxx.xx,localhost,127.0.0.1
```
