### ISSUE TITLE
Random JavaScript error, because of not updated public folder with apache docker image

### ISSUE THREAD

**Issue by pbek** [tobybatch/kimai2#289]
**Describe the bug**

I moved this over from https://github.com/kevinpapst/kimai2/issues/2785.

I'm using the `kimai/kimai2:apache` Docker container to run Kimai 2 with Traefik as ingress controller.

In Firefox 92 or Chrome 93 I get a JavaScript error on e.g. `https://my.domain.com/en/timesheet/`.

![image](https://user-images.githubusercontent.com/1798101/134137465-5407cdcc-bd21-49aa-b0a8-105d712bbb39.png)

Since there doesn't seem to be any js map files around I cannot check where exactly the error is thrown.
And because of the JS error it seems no JS is executed on the page, so I can't `Start again` a time entry. Because if you click on it a `GET` request will be made, instead of a `PATCH` request according to the routes.

```
  restart_timesheet                    PATCH      ANY      ANY    /api/timesheets/{id}/restart                                        
```

Does above JS error ring any bell to you or is there a way to get map files generated to get more information?

**To Reproduce**
1. Go to `https://my.domain.com/en/timesheet/`
2. Click on `Start again` on a time entry
3. See error `Method Not Allowed` on a new page `https://my.domain.com/api/timesheets/185/restart` because of the `GET` request.

**Logfile**

```
[Tue Sep 21 10:31:42.321607 2021] [php:notice] [pid 94] [client 172.19.0.32:57558] [2021-09-21 08:31:42] request.ERROR: Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException: "No route found for "GET /api/timesheets/185/restart": Method Not Allowed (Allow: PATCH)" at /opt/kimai/vendor/symfony/http-kernel/EventListener/RouterListener.php line 140 {"exception":"[object] (Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\MethodNotAllowedHttpException(code: 0): No route found for \\"GET /api/timesheets/185/restart\\": Method Not Allowed (Allow: PATCH) at /opt/kimai/vendor/symfony/http-kernel/EventListener/RouterListener.php:140, Symfony\\\\Component\\\\Routing\\\\Exception\\\\MethodNotAllowedException(code: 0):  at /opt/kimai/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:42)"} [], referer: https://my.domain.com/en/team/timesheet/
```

**Additional context**
 - Kimai version: 1.15.1 stable
 - PHP version: 8
 - Device: KDE Neon
 - Browser Firefox 92, Chrome 93

**Docker config**

```yaml
  kimai:
    image: kimai/kimai2:apache
    depends_on:
      - kimai-mysql
    volumes:
      - kimai-public:/opt/kimai/public
      - kimai-var:/opt/kimai/var
      - ./kimai/local.yaml:/opt/kimai/config/packages/local.yaml
    restart: unless-stopped
    networks:
      - kimai
      - traefik
    environment:
      - TZ=Europe/Vienna
      - TRUSTED_HOSTS=localhost,127.0.0.1,my.domain.com
      - ADMINMAIL=me@my.domain.com
    env_file:
      - ./kimai/variables-kimai.env
    labels:
      - traefik.http.routers.kimai.rule=Host(`my.domain.com`)
      - traefik.http.routers.kimai.tls.certresolver=default
      - traefik.http.routers.kimai.tls=true
      - traefik.http.services.kimai.loadbalancer.server.port=8001
      - traefik.docker.network=server_traefik
```
