### ISSUE TITLE
Update to 1.0 breaks DB schema

### ISSUE THREAD

**Issue by yayitazale** [tobybatch/kimai2#29]
Related to #11, I have updated to 1.0 just using docker compose pull with the tag latest  and I'm getting 500 error on some timesheet pages.

Rolling back to 0.9 worked out, but I want to update to the new 1.0, so I have to update the DB manually?

I have the DATABASE_URL set on docker-compose.yaml correctly.

thanks

**Comment by tobybatch** [comment]
Yes you will need to run the migrations.  Back everything up and then start the q.o container and then shell into the container:

    docker exec -ti NAME bash
 
and run:

    bin/console doctrine:migrations:version --add --all -n

I'll leave this issue open as I will add this to the docker start script.

**Comment by yayitazale** [comment]
It doesn't work. I followed the steps of DB updating:

```
git fetch --tags
git checkout 1.0.1 
composer install --no-dev --optimize-autoloader
bin/console cache:clear --env=prod
bin/console cache:warmup --env=prod
bin/console doctrine:migrations:migrate
```
The comand "git checkout 1.0.1 " says 

> error: Your local changes to the following files would be overwritten by checkout:
>         composer.lock
> Please commit your changes or stash them before you switch branches.
> Aborting

And final step says nothing to migrate.

Running 
`bin/console doctrine:migrations:version --add --all -n`
doesn't make any change, even forcing the recreation of the container.

What I'm doing wrong?

**Comment by tobybatch** [comment]
You shouldn't be pulling into the container.  All changes will be lost when (if) the container restarts unless you are mounting /opt/kimai into a volume.

You should be just need to change the tag in the docker-compose and run a

     docker-compose stop kimai
     docker-compose up --build

The container will re-use the db form the previous version and then run the migrations (https://github.com/tobybatch/kimai2/blob/master/tags/1.0/startup.sh#L71).

However, I just tested this and it failed.  Let me investigate.

**Comment by tobybatch** [comment]
Fix coming soon.  Totally my fault.  I copied instruction from the install docs for kimai without understanding what they did.  In the install kimai creates the DB and then added the DB migrations to the DB **because** the schema is now up to date.  ```/opt/kimai/bin/console -n doctrine:migrations:version --add --all```

What I should have done is **execute** the migations that are needed, ```/opt/kimai/bin/console -n -vv doctrine:migrations:migrate --allow-no-migration```.  I've fixed this and pushed new builds for the 0.9, 1.0 and 1.0.1 container images.

**Comment by yayitazale** [comment]
Thanks, I'll give a try as soon as it is publish.

**Comment by yayitazale** [comment]
This is still not working...

**Comment by tobybatch** [comment]
Can you let me have your docker-compose file please (both before and after the version bump).  Just redact the passwords.

**Comment by yayitazale** [comment]
**Before:**
```
version: '3'
services:

  mydb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiu
      - MYSQL_PASSWORD=kimaip
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
        - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: always

  kimai:
    image: kimai/kimai2:0.9
    environment:
        - APP_ENV=prod
        # These are added to override the the DB URL from env when checking the$
        - DATABASE_URL=mysql://kimaiu:kimaip@mydb/kimai
    depends_on:
        - mydb
    restart: always
    ports:
      - 80:8001

volumes:
  mysql:
```

**After**
```
version: '3'
services:

  mydb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiu
      - MYSQL_PASSWORD=kimaip
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
        - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: always

  kimai:
    image: kimai/kimai2:1.0.1
    environment:
        - APP_ENV=prod
        # These are added to override the the DB URL from env when checking the$
        - DATABASE_URL=mysql://kimaiu:kimaip@mydb/kimai
    depends_on:
        - mydb
    restart: always
    ports:
      - 80:8001

volumes:
  mysql:
```
