### ISSUE TITLE
[apache-prod] Upgrade from 1.14.3 to 1.15.1 failed

### ISSUE THREAD

**Issue by JackHewson** [tobybatch/kimai2#293]
I'm using docker compose with the apache image.

``` 
kimai:
    image: kimai/kimai2:apache-1.14.3-prod
    container_name: kimai
    environment:
      - ADMINMAIL=x
      - ADMINPASS=x
      - DATABASE_URL=x
      - TRUSTED_HOSTS=kimai,localhost,127.0.0.1
    volumes:
      - /data/kimai/var:/opt/kimai/var
    restart: always
``` 

As in https://tobybatch.github.io/kimai2/updating.html described, it just changed the tag name to `1.15.1`:

```
kimai:
    image: kimai/kimai2:apache-1.15.1-prod
    container_name: kimai
    environment:
      - ADMINMAIL=x
      - ADMINPASS=x
      - DATABASE_URL=x
      - TRUSTED_HOSTS=kimai,localhost,127.0.0.1
    volumes:
      - /data/kimai/var:/opt/kimai/var
    restart: always
```

After restarting the container `kimai` I get the following error:

> [2021-09-22 18:03:08] php.CRITICAL: Uncaught Error: Nelmio\\CorsBundle\\EventListener\\CorsListener::__construct(): Argument #1 ($configurationResolver) must be of type Nelmio\\CorsBundle\\Options\\ResolverInterface, Symfony\\Component\\EventDispatcher\\EventDispatcher given, called in /opt/kimai/var/cache/prod/ContainerLeVbWFb/srcApp_KernelProdContainer.php on line 1545 {"exception":"[object] (TypeError(code: 0): Nelmio\\\\CorsBundle\\\\EventListener\\\\CorsListener::__construct(): Argument #1 ($configurationResolver) must be of type Nelmio\\\\CorsBundle\\\\Options\\\\ResolverInterface, Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher given, called in /opt/kimai/var/cache/prod/ContainerLeVbWFb/srcApp_KernelProdContainer.php on line 1545 at /opt/kimai/vendor/nelmio/cors-bundle/EventListener/CorsListener.php:44)"} []

Which additional steps are required to get the update? Thanks!
