### ISSUE TITLE
Column not found: 1054 Unknown column 't0.account' in 'field list'  

### ISSUE THREAD

**Issue by thisfro** [tobybatch/kimai2#296]
I installed kimai2 with this image some time ago and it was working well. Thank you for the great work!

However I tried to login just now and it says **wrong credentials**. I thought something was wrong with the DB but it is up and looks ok.

So I tried to change the password using the console `/opt/kimai/bin/console kimai:user:password` I get:
```
In AbstractMySQLDriver.php line 79:
  An exception occurred while executing 'SELECT t0.id AS id_1, t0.alias AS alias_2, t0.registration_date AS registration_date_3, t0.title AS title_4, t0.avatar AS avatar_5, t0.api_token AS api_token  
  _6, t0.auth AS auth_7, t0.username AS username_8, t0.email AS email_9, t0.account AS account_10, t0.enabled AS enabled_11, t0.password AS password_12, t0.last_login AS last_login_13, t0.confirmati  
  on_token AS confirmation_token_14, t0.password_requested_at AS password_requested_at_15, t0.roles AS roles_16, t0.color AS color_17 FROM kimai2_users t0 WHERE t0.username = ? LIMIT 1' with params   
  ["thisfro"]:                                                                                                                                                                                          
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.account' in 'field list'                                                                                                                   

In Exception.php line 18:
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.account' in 'field list'  

In PDOStatement.php line 112:
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.account' in 'field list'  
```
It also tells me, that there are 14 migrations to execute. The latest I successfully migrated is `DoctrineMigrations\Version20200725213424`. Might `DoctrineMigrations\Version20210704111542` (Cleans up the user table) fix this error?

Or might this be caused by something else?

Thanks for any hints!

**Comment by tobybatch** [comment]
It certainly looks like a db migration issue.

Can you fill in the questions about which container you are using please? In particular I need to see how you are connecting to the DB and which image you are using.

**Comment by thisfro** [comment]
Thank you for your answer!

I use the following docker-compose:
```
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    build: compose
    ports:
      - 9081:80
    volumes:
      - ./compose/nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=
      - ADMINMAIL=
      - ADMINPASS=
      - DATABASE_URL=mysql://user:pass@sqldb/kimai
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped

  postfix:
    image: catatnight/postfix:latest
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    restart: unless-stopped

volumes:
    var:
    public:
```
