### ISSUE TITLE
Question: Delayed docker images for release

### ISSUE THREAD

**Issue by derdeagle** [tobybatch/kimai2#302]
Hi,

I posted the question below in an official Kimai2 discussion and was redirected here, please find my question below.

I wanted to ask whether it is intentional that (as of now) for some releases there is no docker image available. The latest image version on Docker hub currently available is 1.15.2 while 1.15.6 is the latest release.
Are there currently any blocker to release new images or is it a matter of time where assistance is needed?

Thank you!

**Comment by tobybatch** [comment]
I just hadn't noticed the new releases, I was busy with my day job.

The 1.15.6 release is building now. It should be available later today.

**Comment by derdeagle** [comment]
Thank you very much for your fast action!

**Comment by Apfelwurm** [comment]
> I just hadn't noticed the new releases, I was busy with my day job.
> 
> The 1.15.6 release is building now. It should be available later today.

Do you have reasons why you release it manually or could you use help to automate the task in the future ? :)

**Comment by kevinpapst** [comment]
Automation is king and we want it. In the past there were limitations on cross project events in Github actions. So my release couldn't trigger a build here. Do you happen to know if that changed?
If you have input how to build an automation pipeline, yes please: share it! 👍

**Comment by Apfelwurm** [comment]
especially when you have access to both repositories it should be pretty easy using https://github.com/marketplace/actions/dispatch-action like this:

create a personal access token on the Docker repository and store it into the PERSONAL_ACCESS_TOKEN secret and also your DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secret

Kimai2 Repository side:

```
name: trigger_build_docker

on:
  release:
    types: [released]

jobs:
  build:
    name: Dispatch to Kimai Docker
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: kimai2
          owner: tobybatch
          event_type: new_release
```


Docker Repository side

```
name: build_docker

on:
  repository_dispatch:
    types: [new_release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kimai/kimai2:apache
          target: prod
          build-args: |
            "KIMAI=master"
            "BASE=apache"
```


the hacky alternative when you want to keep it localy in the repo and you can use the same release versions / tags:

create your DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secret on the docker repo

```
name: build_docker

on:
  schedule:
    - cron:  '30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install lastversion
      run: sudo apt-get update -y; sudo apt-get install --no-install-recommends -y python3 python3-pip; pip install lastversion
    - name: check remote lastversion
      id: remote_version
      run: echo "::set-output name=version::$(lastversion https://github.com/kevinpapst/kimai2)"    
    - name: check local lastversion
      id: local_version 
      run: echo "::set-output name=version::$(lastversion https://github.com/tobybatch/kimai2)"  
    - name: Login to DockerHub
      if: ${{ steps.remote_version.outputs.version != steps.local_version.outputs.version }}
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      if: ${{ steps.remote_version.outputs.version != steps.local_version.outputs.version }}
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: kimai/kimai2:apache
        target: prod
        build-args: |
          "KIMAI=master"
          "BASE=apache"
    - name: make github release
      if: ${{ steps.remote_version.outputs.version != steps.local_remote_version.outputs.version }}
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.remote_version.outputs.version }}
        tag_name: ${{ steps.remote_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

```
The bad thing about this is, the schedule gets disabled if there is no activity on the repo in 4 weeks, so the first approach is better for sure.

Disclaimer: quickly hacked both together without testing :D
