### ISSUE TITLE
Plugin Errors

### ISSUE THREAD

**Issue by DustyArmstrong** [tobybatch/kimai2#307]
**Describe the bug**

When trying to install a plugin, the plugin is detected however gives the following error from the logs. 

`Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT COUNT(*) FROM kimai2_expense_category t0 WHERE t0.visible = ?' with params [1]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kimai.kimai2_expense_category' doesn't exist" at /opt/kimai/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 61`

**To Reproduce**

Install a plugin to Kimai, at the ` /opt/kimai/var/plugins/ExpensesBundle` location, reload Kimai. 

**Desktop (please complete the following information):**
 - OS: Debian
 - Docker version: 20.10.8, build 3967b7d
 - Docker compose version: 1.29.2, build 5becea4c

**Command used to run the container**

`docker-compose up -d`

**Docker compose file**

I run the container alongside a lot of others, but the relevant aspects (SQL, Nginx, Kimai) are essentially the same as the compose file in this repository. 

```yaml
kimai: 
	image: kimai/kimai2:fpm
	container_name: "kimai"
	environment:
		- DATABASE_URL=mysql://user:details@sqldb/kimai
		- TRUSTED_HOSTS=nginx,localhost,127.0.0.1
	volumes:
		- public:/opt/kimai/public
		- plugins:/opt/kimai/plugins
	restart: unless-stopped
	networks:
		- "mynetwork"
```
