### ISSUE TITLE
Kimai2 Apache Service is looping installation / update[BUG] 

### ISSUE THREAD

**Issue by NK0D1NG** [tobybatch/kimai2#352]
**Describe the bug**
I got Kimai2 up and running in a Docker Swarm Cluster. It was running for some hours. But now the Service just keeps restarting the init/update procedure. The service container does not get up healthy correctly anymore (replicated 0/1). The database service is up and running perfectly without problems.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the Apache image (prod)
2. Deploy via Docker Swarm
3. Run the service a few hours
4. Watch the logs / service status

**System (please complete the following information):**
 - OS: Ubuntu Server 20.04 (LTS)
 - Docker version: 20.10.12
 - Docker compose version: 1.27.4

**Docker compose file (with passwords redacted)**

```yaml
version: "3.5"
services:
  kimai:
    image: kimai/kimai2:apache
    environment:
      - ADMINMAIL=info@mydomain.de
      - ADMINPASS=adminpass
      - DATABASE_URL=mysql://kimaiuser:dbpassword@db/kimai
      - TRUSTED_HOSTS=nginx,kimai,db,localhost,127.0.0.1
    volumes:
      - kimai-app:/opt/kimai/var
    networks:
      - kimai
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - traefik.http.routers.kimai-http.rule=Host(`kimai.mydomain.de`)
        - traefik.http.routers.kimai-http.entrypoints=http
        - traefik.http.routers.kimai-http.middlewares=https-redirect
        - "traefik.http.routers.kimai-https.rule=Host(`kimai.mydomain.de`)"
        - "traefik.http.routers.kimai-https.tls=true"
        - "traefik.http.routers.kimai-https.tls.certresolver=mycertresolver"
        - "traefik.http.routers.kimai-https.entrypoints=https"
        - "traefik.http.services.kimai.loadbalancer.server.port=8001"
    ports:
      - 8001:8001

  db:
    image: mysql:5.7
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=dbrootpassword
    volumes:
      - kimai-db:/var/lib/mysql
    command: --default-storage-engine innodb
    healthcheck:
      test: mysqladmin -pdbrootpassword ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - kimai

volumes:
  kimai-db:
    driver_opts:
      type: "nfs"
      o: "addr=nfsip,nolock,soft,rw"
      device: ":/srv/storage/kimai/db"

  kimai-app:
    driver_opts:
      type: "nfs"
      o: "addr=nfsip,nolock,soft,rw"
      device: ":/srv/storage/kimai/app"

networks:
  traefik-public:
    external: true
  kimai:
    driver: overlay
```

**Additional context**
The logs show the repeating install/update/cache process which is looping forever:
```

kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    | Kimai installation running ...
kimai_kimai.1.antiyq3mx6eomyhost    | ==============================
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  ! [NOTE] Database is existing and connection could be established 
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  [OK] Already at the latest version ("DoctrineMigrations\Version20220101204501")
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  Rebuilding your cache, please be patient ...
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  // Clearing the cache for the prod environment with debug         
kimai_kimai.1.antiyq3mx6eomyhost    |  // false                                                          
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  ! [NOTE] For better performances, you should move the cache and log directories
kimai_kimai.1.antiyq3mx6eomyhost    |  !        to a non-shared folder of the VM.                        
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  // Warming up the cache for the prod environment with debug       
kimai_kimai.1.antiyq3mx6eomyhost    |  // false                                                          
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  [OK] Congratulations! Successfully installed Kimai version 1.18.1 
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    | Kimai updates running ...
kimai_kimai.1.antiyq3mx6eomyhost    | =========================
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  [OK] Already at the latest version ("DoctrineMigrations\Version20220101204501")
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  Rebuilding your cache, please be patient ...
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.antiyq3mx6eomyhost    |  // Clearing the cache for the prod environment with debug         
kimai_kimai.1.antiyq3mx6eomyhost    |  // false                                                          
kimai_kimai.1.antiyq3mx6eomyhost    |
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    | Wait for MySQL DB connection ...
kimai_kimai.1.l10feja9k0armyhost    | Testing DB:** new \PDO(mysql:host=db;dbname=kimai;port=3306, kimaiuser, dbpassword, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    | Kimai installation running ...
kimai_kimai.1.l10feja9k0armyhost    | ==============================
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    | Database `kimai` for connection named default already exists. Skipped.
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  [OK] Already at the latest version ("DoctrineMigrations\Version20220101204501")
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  Rebuilding your cache, please be patient ...
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  // Clearing the cache for the prod environment with debug         
kimai_kimai.1.l10feja9k0armyhost    |  // false                                                          
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  ! [NOTE] For better performances, you should move the cache and log directories
kimai_kimai.1.l10feja9k0armyhost    |  !        to a non-shared folder of the VM.                        
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  // Warming up the cache for the prod environment with debug       
kimai_kimai.1.l10feja9k0armyhost    |  // false                                                          
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  [OK] Congratulations! Successfully installed Kimai version 1.18.1 
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    | Kimai updates running ...
kimai_kimai.1.l10feja9k0armyhost    | =========================
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  [OK] Already at the latest version ("DoctrineMigrations\Version20220101204501")
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  Rebuilding your cache, please be patient ...
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.l10feja9k0armyhost    |  // Clearing the cache for the prod environment with debug         
kimai_kimai.1.l10feja9k0armyhost    |  // false                                                          
kimai_kimai.1.l10feja9k0armyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    | Wait for MySQL DB connection ...
kimai_kimai.1.g5645bbj2gmvmyhost    | Testing DB:** new \PDO(mysql:host=db;dbname=kimai;port=3306, kimaiuser, dbpassword, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    | Kimai installation running ...
kimai_kimai.1.g5645bbj2gmvmyhost    | ==============================
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  ! [NOTE] Database is existing and connection could be established 
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  [OK] Already at the latest version ("DoctrineMigrations\Version20220101204501")
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  Rebuilding your cache, please be patient ...
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  // Clearing the cache for the prod environment with debug         
kimai_kimai.1.g5645bbj2gmvmyhost    |  // false                                                          
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  ! [NOTE] For better performances, you should move the cache and log directories
kimai_kimai.1.g5645bbj2gmvmyhost    |  !        to a non-shared folder of the VM.                        
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  // Warming up the cache for the prod environment with debug       
kimai_kimai.1.g5645bbj2gmvmyhost    |  // false                                                          
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  [OK] Congratulations! Successfully installed Kimai version 1.18.1 
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    | Kimai updates running ...
kimai_kimai.1.g5645bbj2gmvmyhost    | =========================
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  [OK] Already at the latest version ("DoctrineMigrations\Version20220101204501")
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  Rebuilding your cache, please be patient ...
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.g5645bbj2gmvmyhost    |  // Clearing the cache for the prod environment with debug         
kimai_kimai.1.g5645bbj2gmvmyhost    |  // false                                                          
kimai_kimai.1.g5645bbj2gmvmyhost    |
kimai_kimai.1.52uxk6dr33fbmyhost    |
kimai_kimai.1.52uxk6dr33fbmyhost    | Wait for MySQL DB connection ...
kimai_kimai.1.52uxk6dr33fbmyhost    | Testing DB:** new \PDO(mysql:host=db;dbname=kimai;port=3306, kimaiuser, dbpassword, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established
kimai_kimai.1.52uxk6dr33fbmyhost    |
kimai_kimai.1.52uxk6dr33fbmyhost    | Kimai installation running ...
kimai_kimai.1.52uxk6dr33fbmyhost    | ==============================
kimai_kimai.1.52uxk6dr33fbmyhost    |
kimai_kimai.1.52uxk6dr33fbmyhost    |  ! [NOTE] Database is existing and connection could be established 
kimai_kimai.1.52uxk6dr33fbmyhost    |
kimai_kimai.1.52uxk6dr33fbmyhost    |
kimai_kimai.1.52uxk6dr33fbmyhost    |  [OK] Already at the latest version ("DoctrineMigrations\Version20220101204501")
kimai_kimai.1.52uxk6dr33fbmyhost    |
kimai_kimai.1.52uxk6dr33fbmyhost    |
kimai_kimai.1.52uxk6dr33fbmyhost    |  Rebuilding your cache, please be patient ...
kimai_kimai.1.52uxk6dr33fbmyhost    |
kimai_kimai.1.52uxk6dr33fbmyhost    |  // Clearing the cache for the prod environment with debug         
kimai_kimai.1.52uxk6dr33fbmyhost    |  // false                                                          
kimai_kimai.1.52uxk6dr33fbmyhost    |

```

**Comment by NK0D1NG** [comment]
For me the error seems to be in the startup.sh:
```
function handleStartup() {
  # These are idempotent, run them anyway
  tar -zx -C /opt/kimai -f /var/tmp/public.tgz 
  /opt/kimai/bin/console -n kimai:install
  /opt/kimai/bin/console -n kimai:update
  if [ ! -z "$ADMINPASS" ] && [ ! -a "$ADMINMAIL" ]; then
    /opt/kimai/bin/console kimai:create-user superadmin $ADMINMAIL ROLE_SUPER_ADMIN $ADMINPASS
  fi
  export KIMAI=$(/opt/kimai/bin/console kimai:version --short)
  echo $KIMAI > /opt/kimai/var/installed
  echo "Kimai2 ready"
}
```

It seems like everything after the if-clause is not reached, because those echo commands are never output to the console. MAybe the kimai:update fails but does not output any errors?

**Comment by tobybatch** [comment]
I don't use docker swarm so I'm not sure what is happening. but it looks like the image is crashing as it either installs or updates.

Can you try starting the kimai image with `entry-point /bin/sh` then shell in and run the commands in the start up shell by hand?

**Comment by NK0D1NG** [comment]
I tried by addin this in the Docker-Compose File:
```

version: "3.5"
services:
  app:
    image: kimai/kimai2:apache-1.18.1-prod
    environment:
      - ADMINMAIL=info@nkoding.de
      - ADMINPASS=9ubxYHMTFDqZVsfY
      - DATABASE_URL=mysql://kimaiuser:mydbpassword@db/kimai
      - TRUSTED_HOSTS=nginx,kimai,db,localhost,127.0.0.1
    volumes:
      - kimai-app:/opt/kimai/var
    **entrypoint: /bin/sh**
```

But that leads to the server not being started and I don't see any containers running the image via `docker ps`
