### ISSUE TITLE
Can't connect to my kimai server using my web browser [BUG] 

### ISSUE THREAD

**Issue by bellakhal4med** [tobybatch/kimai2#355]
**Describe the bug**
Hello all, 
I'm trying to run the apache prod kimai server using the docker-compose file provided in "https://github.com/tobybatch/kimai2/tree/main/compose/docker-compose.apache.prod.yml" . When I try to connect to the server  on my web browser I get the following error : "Error: connect ECONNREFUSED 127.0.0.1:8001" (I also tried to ping the same address using postman and other browsers)

**Command used to run the container**
 - docker-compose -f docker-compose.apache.prod.yml up  -d
 
**To Reproduce**
Steps to reproduce the behaviour:
1. Start the containers with docker-compose
2. ping 127.0.0.1:8001
3. Container logs for " kimai/kimai2:apache ":  
localhost:8001 127.0.0.1 - - [09/Mar/2022:14:43:40 +0000] "GET / HTTP/1.1" 302 588 "-" "curl/7.64.0"
localhost:8001 127.0.0.1 - - [09/Mar/2022:14:44:00 +0000] "GET / HTTP/1.1" 302 588 "-" "curl/7.64.0"
localhost:8001 127.0.0.1 - - [09/Mar/2022:14:44:21 +0000] "GET / HTTP/1.1" 302 588 "-" "curl/7.64.0"
localhost:8001 127.0.0.1 - - [09/Mar/2022:14:44:41 +0000] "GET / HTTP/1.1" 302 588 "-" "curl/7.64.0"
localhost:8001 127.0.0.1 - - [09/Mar/2022:14:45:01 +0000] "GET / HTTP/1.1" 302 588 "-" "curl/7.64.0"
localhost:8001 127.0.0.1 - - [09/Mar/2022:14:45:21 +0000] "GET / HTTP/1.1" 302 588 "-" "curl/7.64.0"
localhost:8001 127.0.0.1 - - [09/Mar/2022:14:45:41 +0000] "GET / HTTP/1.1" 302 588 "-" "curl/7.64.0"
localhost:8001 127.0.0.1 - - [09/Mar/2022:14:46:01 +0000] "GET / HTTP/1.1" 302 588 "-" "curl/7.64.0"
localhost:8001 127.0.0.1 - - [09/Mar/2022:14:46:22 +0000] "GET / HTTP/1.1" 302 588 "-" "curl/7.64.0"
4. error: 
Error: connect ECONNREFUSED 127.0.0.1:8001

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Docker version: 19.03.1
 - Docker compose version: 1.24.1,

**Docker compose file (with passwords redacted)**
```
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    volumes:
      - kimai-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=****
      - MYSQL_ROOT_PASSWORD=****
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache
    volumes:
      - kimai-var:/opt/kimai/var
    ports:
      - 8001:8001
    environment:
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    restart: unless-stopped

volumes:
  kimai-var:
  kimai-mysql:
```

Thank you. 
Best Regards,
