### ISSUE TITLE
[BUG] Full-dockerized version poses problem

### ISSUE THREAD

**Issue by 3isenHeiM** [tobybatch/kimai2#385]
**Describe the bug**
I've built the docker-compose stack relying on public base images (php-fpm & nginx), in a very docker. Every micro-service is a separate container.

However, i get errors on the nginx container, that fails to serve files and throwing this error :
```
192.168.176.1 - - [31/May/2022:09:43:53 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"

2022/05/31 09:43:53 [error] 30#30: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/index.php on line 8PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/vendor/autoload.php' (include_path='.:/opt/bitnami/php/lib/php') in /var/www/html/index.php:8


}

  thrown in /var/www/html/index.php on line 8" while reading response header from upstream, client: 192.168.176.1, server: kimai.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.176.3:9000", host: "localhost:9999"
```

The tab shows the favicon correctly, I take that as a proof that the Nginx stack works well. However on the PHP side there is a problem. I've mounted the content of the `/opt/kimai/public/` in the `/var/www/html` folder, but apparently it looks for a file outside of this directory (`vendor/autoload.php`).

However, mounting the `/opt/kimai/public/` should be sufficient, as per all the other docker-compose files of Kimai I've seen...

**To Reproduce**
1. Save this docker-compose file
2. Launch the stack with the `docker-compose up -d` command
3. Head over to `http://localhost:9999` to browse to kimai
4. Empty page.

**Desktop (please complete the following information):**
 - OS: Debian latest
 - Docker version: 20.10.16
 - Docker compose version: 2.5.0

**Command used to run the container**
 - `docker-compose up -d`

**Docker compose file (with passwords redacted)**

```yaml
version: '3.6'
services:
  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:fpm
    environment:
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@kiami-sqldb/kimai
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    volumes:
      - kimai_public:/opt/kimai/public

    depends_on:
      - kimai-nginx
      - sqldb
    restart: unless-stopped
    networks:
      - kimai

  kimai-nginx:
    image: nginx:latest
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - kimai_public:/var/www/html
      - logs-web:/var/log/nginx
    depends_on:
      - kimai-php
    ports:
      - 9999:80
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - kimai


  kimai-php:
    image: 'bitnami/php-fpm:latest'
    volumes:
      - kimai_public:/var/www/html
      - logs-php-fpm:/var/log/php-fpm
    depends_on:
      - kiami-sqldb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - kimai


  kiami-sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - database:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - kimai

volumes:
  kimai_public:
  logs-php-fpm:
  logs-web:
  database:


networks:
   kimai:
```

**Comment by tobybatch** [comment]
Why use this image?

```
  kimai-php:
    image: 'bitnami/php-fpm:latest'
    volumes:
      - kimai_public:/var/www/html
      - logs-php-fpm:/var/log/php-fpm
    depends_on:
      - kiami-sqldb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - kimai
    
```

The `kimai/kimai2:fpm` image has php-fpm build into it. Have you tried just running this `docker-compose.yml`?

**Comment by 3isenHeiM** [comment]
I was not aware of this, thanks for the heads-up ! ;)

However, the standard nginx container does not work either, for instance with this `docker-compose.yml` :

```yaml
version: '3.6'
services:
  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:fpm-latest
    environment:
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@kiami-sqldb/kimai
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    volumes:
      - kimai_public:/opt/kimai/public
    depends_on:
      - kimai-nginx
      - kiami-sqldb
    restart: unless-stopped

  kimai-nginx:
    image: nginx:latest
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - kimai_public:/var/www/html
      - logs-web:/var/log/nginx
    ports:
      - 9999:80
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  kiami-sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - database:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

volumes:
  kimai_public:
  logs-php-fpm:
  logs-web:
  database:
```

I don't know why the official nginx image can't do the trick, and that's something I'd like to achieve (being able to use the latest nginx image0.

Here is the nginx config file I's mounting:

```
server {
    listen 80;
    index index.php index.html;
    server_name kimai.localhost;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass kimai:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

Running this gives me the error in the kimai container logs :

```
31 12:21:50 [error] 31#31: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: kimai.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "localhost:9999"
```

And I get a 404 file not found when heading to the bound port (TCP 9999).

Again here the favicon is loaded, so I suspect a PHP-FPM error. I checked the hostname for connecting to the php instance and it seems correct.
