### ISSUE TITLE
[BUG] Error reloading cache: Cannot autowire service

### ISSUE THREAD

**Issue by varunpan** [tobybatch/kimai2#405]
**Describe the bug**
I pulled new image and now getting an error when reloading cache.
I attempted to manually rebuild the cache and getting the same error when running the cache:clear and cache:warmup or any another bin/console functions.

**To Reproduce**
1. `docker pull kimai`
2. reloaded cache: `docker exec -ti kimai /opt/kimai/bin/console kimai:reload --env=prod`
3. See error:
```
In DefinitionErrorExceptionPass.php line 54:
                                                                                                               
  Cannot autowire service "App\Utils\MPdfConverter": argument "$cacheDirectory" of method "__construct()" is   
  type-hinted "string", you should configure its value explicitly.
```

**Additional context**
 - Kimai version: Not sure, unable to run any bin/console functions
 - PHP version: 8.1.9
 - Device: Linux 5.18.0-0.deb11.3-amd64 Debian
 - Browser Firefox 104

**Comment by tobybatch** [comment]
I don't understand this. `kimai` isn't the correct image name.

Can you show the output of this command please?

```
docker ps -a | grep kimai
```

**Comment by varunpan** [comment]
Im sorry it was `docker pull kimai2:fpm`

**Comment by tobybatch** [comment]
Is this started as a docker-compose tear up? what is running the web proxy for the FPM instance?

And I guess it's actually

```
docker pull kimai/kimai2:fpm
```

**Comment by tobybatch** [comment]
Can you post the output of 

```
docker ps -a
```

**Comment by kevinpapst** [comment]
@tobybatch It is correct that the service definition was changed for this release, see line:
https://github.com/kevinpapst/kimai2/blob/master/config/services.yaml#L59

But it is not correct that this error is thrown. Can't tell you if this is some kind of weird cache problem or an update problem though. The only idea I have is to remove the existing cache with a hard `rm -rf /opt/kimai/var/cache/prod/*`, followed by the "soft reload" command.

**Comment by varunpan** [comment]
sure it is:

```
CONTAINER ID   IMAGE                               COMMAND                  CREATED        STATUS                  PORTS                                   NAMES
74e091e1fb43   tobybatch/nginx-fpm-reverse-proxy   "nginx -g 'daemon of…"   10 hours ago   Up 10 hours             0.0.0.0:8008->80/tcp, :::8008->80/tcp   kimai_server
f1415ba830e5   kimai/kimai2:fpm                    "/bin/sh -c /startup…"   10 hours ago   Up 10 hours (healthy)   9000/tcp                                kimai
683f59f62bae   mysql:5.7                           "docker-entrypoint.s…"   10 hours ago   Up 10 hours (healthy)   3306/tcp, 33060/tcp                     kimai_db
3f164583988b   catatnight/postfix:latest           "/bin/sh -c '/opt/in…"   10 hours ago   Up 10 hours                                                     kimai_postfix

```

**Comment by varunpan** [comment]
> The only idea I have is to remove the existing cache with a hard rm -rf /opt/kimai/var/cache/prod/*, followed by the "soft reload" command.

I did remove manually remove the cache and tried to manually rebuild the cache, but getting the same error when trying to run any type of bin/console command.

**Comment by varunpan** [comment]
> Is this started as a docker-compose tear up? what is running the web proxy for the FPM instance?

Yes, see below my docker compose file:

```
version: '3.5'
networks:
  panchnet:
    external: true
services:
  sqldb:
    image: mysql:5.7
    container_name: kimai_db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/docker/kimai/mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      panchnet:
        ipv4_address: 172.18.5.247

  server:
    image: tobybatch/nginx-fpm-reverse-proxy
    container_name: kimai_server
    ports:
      - 8008:80
    volumes:
      - /home/docker/kimai/public:/opt/kimai/public:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    restart: unless-stopped
    depends_on:
      - kimai
#    healthcheck:
#      test:  wget --spider http://nginx/health || exit 1
#      interval: 20s
#      start_period: 10s
#      timeout: 10s
#      retries: 3
    networks:
      panchnet:
        ipv4_address: 172.18.5.246

  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:fpm
    container_name: kimai
    environment:
      - ADMINMAIL=${ADMINMAIL}
      - ADMINPASS=${ADMINPASS}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sqldb/${MYSQL_DATABASE}
      - TRUSTED_HOSTS=server,192.168.1.4,172.18.5.199,kimai.panchnet.duckdns.org
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/docker/kimai/public:/opt/kimai/public
      - /home/docker/kimai/var:/opt/kimai/var
      - /home/docker/kimai/config:/opt/kimai/config
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    depends_on:
      - sqldb
    restart: unless-stopped
    networks:
      panchnet:
        ipv4_address: 172.18.5.245

  postfix:
    image: catatnight/postfix:latest
    container_name: kimai_postfix
    environment:
      maildomain: panchnet.duckdns.org
      smtp_user: ${MYSQL_USER}:${MYSQL_PASSWORD}
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    restart: unless-stopped
    networks:
      panchnet:
        ipv4_address: 172.18.5.244
```
