### ISSUE TITLE
[BUG] docker-compose logs gets spammed with 127.0.0.1 -  [...] +0000 "GET /ping" 404

### ISSUE THREAD

**Issue by alexanderpas** [tobybatch/kimai2#439]
Using docker compose with the PHP FPM container and a reverse proxy in a seperate container, the docker logs get spammed with pings.

For reference, the docker-compose file:

```
version: '3.5'
services:

  kimai-database:
    image: mariadb:10.3
    container_name: kimai-database
    environment:
      - MYSQL_USER=${MYSQL_USER:-kimai}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-kimai}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-kimai}
      - MARIADB_RANDOM_ROOT_PASSWORD=${MARIADB_RANDOM_ROOT_PASSWORD:-true}
    env_file:
      - .env
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped

  kimai-webserver:
    image: nginx:1.22-alpine
    container_name: kimai-webserver
    ports:
      - ${MAIN_PORT:-80}:80
    env_file:
      - .env
    volumes:
      - ./kimai-public:/opt/kimai/public:ro
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - kimai-php

  kimai-php:
    image: kimai/kimai2:fpm-1.28.1-prod
    container_name: kimai-php
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER:-kimai}:${MYSQL_PASSWORD:-kimai}@kimai-database/${MYSQL_DATABASE:-kimai}
      - TRUSTED_HOSTS=${TRUSTED_HOSTNAME:-localhost},kimai-webserver,localhost,127.0.0.1
    env_file:
      - .env
    volumes:
      - ./kimai-public:/opt/kimai/public
      - ./kimai-data:/opt/kimai/var
    restart: unless-stopped
    depends_on:
      - kimai-database
```
