### ISSUE TITLE
Kimai main repository changes

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#442]
Hi @tobybatch 

I used the "holiday" to perform some very long outstanding tasks and with it came some changes that (might) affect the Docker / build process:

- the repository was moved to https://github.com/kimai/kimai
- the main branch changed from `master` to `main`
- I merged the new major release into `main` and created a "pre-release" (which does not trigger a new docker image build) at https://github.com/kimai/kimai/releases/tag/2.0.0-alpha

I hope that the same image can be used for the 1.x and 2.x branch. 2.x now requires PHP 8.1, which 1.x already supported, so we should be good on that end. I need support with testing especially LDAP (the entire security system was rewritten, because I switched internally from Symfony 4 to Symfony 6). 

Obviously everyone wants a stable and fully tested new release, but my own use-cases are limited and I hope we can create a "alpha" release docker-images for testing? 
What can I do to help here?

**Comment by tobybatch** [comment]
Yes, of course I can help with testing. To run the same image, it really relies on using the same version of php for both branches.

Does the 1.x version support PHP 8.1? If it does it'll be a doddle.

I will take look and try some manual builds later today.

**Comment by kevinpapst** [comment]
That would be awesome. Yes, we can run both version with 8.1. 

Regarding the tests: I hope the community will do that, once we offer images :)
It is only LDAP that I wasn't able to test properly. You use LDAP, don't you?

**Comment by tobybatch** [comment]
OK, so the Dockerfile now (I think) supports 1.x and 2.x builds. I just pushed 2.0.0 alpha images to docker hub.

I'll look at the GH actions. I'm pretty sure they can track the 2.x pre releases and 1.x builds at the same time.

```
 docker push kimai/kimai2:apache-2.0.0-alpha-prod
 docker push kimai/kimai2:apache-2.0.0-alpha-dev
 docker push kimai/kimai2:fpm-2.0.0-alpha-prod
 docker push kimai/kimai2:fpm-2.0.0-alpha-dev
```

**Comment by kevinpapst** [comment]
> OK, so the Dockerfile now (I think) supports 1.x and 2.x builds. I just pushed 2.0.0 alpha images to docker hub.

Super cool, that was quick 👍 

> I'll look at the GH actions. I'm pretty sure they can track the 2.x pre releases and 1.x builds at the same time.

I think this is caused by my action, which only triggers on "release" and not "pre-release":
https://github.com/kimai/kimai/blob/main/.github/workflows/docker.yaml#L3

Not sure if we want pre-releases. But if the name does not cause any harm, then we I could change it on my end.

**Comment by tobybatch** [comment]
@kevinpapst  So trying to start the LDAP enabled container we use at Neontribe with v2 alpha I get this:

```
kimai_1    |  [ERROR] You are not allowed to define new elements for path                    
kimai_1    |          "security.firewalls". Please define all elements for this path in one  
kimai_1    |          config file.      
```

Are there new instructions for the security provider. Just point me in the right direction.

Here is the redacted local.conf

```yaml
kimai:
    timesheet:
        mode: duration_only


    defaults:
        customer:
            timezone: Europe/London
            country: GB
            currency: GBP

    ldap:
        activate: true
        connection:
            host: 192.168.XX.YY
            username: cn=admin,dc=neontribe,dc=net
            password: XXXXXXXXXXXXXXXXXX
            bindRequiresDn: true
            optReferrals: false

        user:
            baseDn: ou=users,dc=neontribe,dc=net
            usernameAttribute: uid
            attributes:
                - { ldap_attr: "uid", user_method: setUsername }
                - { ldap_attr: "mail", user_method: setEmail }
                - { ldap_attr: cn, user_method: setAlias }
        role:
            baseDn: ou=groups,dc=neontribe,dc=net
            filter: (&(objectClass=posixGroup))
            usernameAttribute: uid
            nameAttribute: cn
            userDnAttribute: memberUid
            groups:
                - { ldap_value: kimai-teamleader, role: ROLE_TEAMLEAD }
                - { ldap_value: kimai-admin, role: ROLE_ADMIN }
                - { ldap_value: kimai-superadmin, role: ROLE_SUPERADMIN }

    # Remove local passwords
    user:
        registration: false
        password_reset: false
    permissions:
        roles:
            ROLE_USER: ['!password_own_profile']
            ROLE_TEAMLEAD: ['!password_own_profile']
            ROLE_ADMIN: ['!password_own_profile']

security:
    providers:
        chain_provider:
            chain:
                providers: [kimai_ldap]
    firewalls:
        secured_area:
            kimai_ldap: ~

```

**Comment by kevinpapst** [comment]
The part 
```
security:
    providers:
        chain_provider:
            chain:
                providers: [kimai_ldap]
    firewalls:
        secured_area:
            kimai_ldap: ~
```

is IMO not necessary since 1.15 😁 see https://github.com/kimai/kimai/blob/main/UPGRADING.md#115

But you can remove it for sure with 2.0 

Check also docs at: https://www.kimai.org/documentation/ldap.html

**Comment by tobybatch** [comment]
@kevinpapst I just tested the LDAP and it works with our set up at Neontribe.  For reference I'll include our redacted local.yaml

```yaml
kimai:
    timesheet:
        mode: duration_only

    defaults:
        customer:
            timezone: Europe/London
            country: GB
            currency: GBP

    ldap:
        activate: true
        connection:
            host: 192.168.21.97
            username: cn=admin,dc=neontribe,dc=net
            password: XXXXXXXXXXXXXXXXXXXXXXXXX
            bindRequiresDn: true
            optReferrals: false

        user:
            baseDn: ou=users,dc=neontribe,dc=net
            usernameAttribute: uid
            attributes:
                - { ldap_attr: "uid", user_method: setUsername }
                - { ldap_attr: "mail", user_method: setEmail }
                - { ldap_attr: cn, user_method: setAlias }
        role:
            baseDn: ou=groups,dc=neontribe,dc=net
            filter: (&(objectClass=posixGroup))
            usernameAttribute: uid
            nameAttribute: cn
            userDnAttribute: memberUid
            groups:
                - { ldap_value: kimai-teamleader, role: ROLE_TEAMLEAD }
                - { ldap_value: kimai-admin, role: ROLE_ADMIN }
                - { ldap_value: kimai-superadmin, role: ROLE_SUPERADMIN }

    # Remove local passwords
    user:
        registration: false
        password_reset: false
    permissions:
        roles:
            ROLE_USER: ['!password_own_profile']
            ROLE_TEAMLEAD: ['!password_own_profile']
            ROLE_ADMIN: ['!password_own_profile']

```
