### ISSUE TITLE
[BUG] vesion 2.x mis-tagged as 1.xx

### ISSUE THREAD

**Issue by marcus905** [tobybatch/kimai2#467]
**Describe the bug**
After updating from 1.30.5 to latest the container doesn't start and the app returns 500.

Most probably the apache tag now mistakenly points to 2.0.0

Logs:
running
```
localhost:8001 127.0.0.1 - - [09/Feb/2023:17:31:50 +0100] "GET / HTTP/1.1" 500 211 "-" "curl/7.64.0"
[Thu Feb 09 17:32:10.228992 2023] [php:error] [pid 54] [client 127.0.0.1:45594] PHP Fatal error:  Uncaught Error: Undefined constant Symfony\\Component\\HttpFoundation\\Request::HEADER_X_FORWARDED_ALL in /opt/kimai/public/index.php:23\nStack trace:\n#0 {main}\n  thrown in /opt/kimai/public/index.php on line 23
```
after a restart
```
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/fonts/fa-regular-400.eot: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/fonts/fa-brands-400.eot: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/fonts/fa-brands-400.woff: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/fonts/fa-brands-400.ttf: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/fonts/fa-solid-900.woff2: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/fonts/fa-brands-400.woff2: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/fonts/fa-solid-900.woff: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/fonts/fa-regular-400.woff: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/tabler.js: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/manifest.json: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/tabler-rtl.js.LICENSE.txt: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/tabler.css: Cannot open: No such file or directory
tar: public/bundles/tabler: Cannot mkdir: Permission denied
tar: public/bundles/tabler/tabler.js.LICENSE.txt: Cannot open: No such file or directory
tar: public/bundles: Cannot utime: Operation not permitted
tar: public: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Kimai installation running ...
==============================
Database `kimai` for connection named default already exists. Skipped.
 [OK] Already at the latest version ("DoctrineMigrations\Version20230126002049")
 Rebuilding your cache, please be patient ...
 // Clearing the cache for the prod environment with debug false                
 [ERROR] Failed to clear cache: Failed to remove file                           
         "/opt/kimai/var/cache/..41Y/pools/system/-zSvM4yc9c/B/Y/86oFB6EKJ3qXDOp
         obJwA":                                                                
         unlink(/opt/kimai/var/cache/..41Y/pools/system/-zSvM4yc9c/B/Y/86oFB6EKJ
         3qXDOpobJwA): Permission denied                                        
 [OK] Congratulations! Successfully installed Kimai version 2.0.0               
Kimai updates running ...
=========================
 [OK] Already at the latest version ("DoctrineMigrations\Version20230126002049")
 Rebuilding your cache, please be patient ...
 // Clearing the cache for the prod environment with debug false                
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /opt/kimai/vendor/twig/twig/src/Compiler.php on line 108
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/var-dumper/Dumper/CliDumper.php on line 1
                                                     
  The command "kimai:reset:locales" does not exist.  
                                                     

Kimai2 ready
Reloading configurations ...
============================
 [OK] All 25 YAML files contain valid syntax.                                   
 [OK] All 513 XLIFF files contain valid syntax.                                 
 Rebuilding your cache, please be patient ...
 // Clearing the cache for the prod environment with debug false                
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/var/cache/pro_/twig/cb/cb06d92a2f750d1e03d3d938724f96b7.php on line 288
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/var-dumper/Dumper/CliDumper.php on line 1
[Thu Feb 09 17:35:34.393199 2023] [core:warn] [pid 42] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Feb 09 17:35:34.396156 2023] [mpm_prefork:notice] [pid 42] AH00163: Apache/2.4.38 (Debian) PHP/8.1.12 configured -- resuming normal operations
[Thu Feb 09 17:35:34.396189 2023] [core:notice] [pid 42] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the container with apache as update from 1.30.5
2. Connect to app

**Desktop (please complete the following information):**
 - OS: Ubuntu server 20.04
 - Docker version: 23.0.0

**Command used to run the container**
 - docker compose

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: redacted
      MYSQL_USER: redacted
      MYSQL_PASSWORD: redacted
      MYSQL_ROOT_PASSWORD: edacted
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped

  kimai:
    image: kimai/kimai2:apache
    environment:
      ADMINMAIL: redacted
      ADMINPASS: redacted
      DATABASE_URL: redacted
      VIRTUAL_HOST: redacted.example.com
      VIRTUAL_PORT: 8001
      TRUSTED_HOSTS: localhost,127.0.0.1,REMOTE_ADDR,redacted.example.com
    depends_on:
      - mysql
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    networks:
      - default
      - nginx-internal

volumes:
    var:
    public:
    mysql:

networks:
  nginx-internal:
```
