### ISSUE TITLE
Error 500 after update to 1.5

### ISSUE THREAD

**Issue by yayitazale** [tobybatch/kimai2#48]
I'm getting this error 500 after updating to 1.5

![imagen](https://user-images.githubusercontent.com/6462849/70513582-3897ab00-1b32-11ea-8c8f-c56e9d0c178f.png)

I just changed the kimai image base from 

`kimai/kimai2:apache-debian-master`

to 

`kimai/kimai2:apache-debian-1.5-prod`

¿What I'm doing wrong?

**Comment by tobybatch** [comment]
Can you please share:
 1. the command you use to start the container.
 1. docker compose (if used) file with any passwords redacted.
 1. The log/cli output of the failed container,

**Comment by yayitazale** [comment]
1. 
`sudo docker-compose pull && sudo docker-compose up -d --build`
2. 
```
version: '3.5'
services:
  mydb:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
 kimai:
    image: kimai/kimai2:apache-debian-1.5-prod
    environment:
      - APP_ENV=prod
    depends_on:
     - mydb
    restart: unless-stopped
    ports:
      - 80:8001

volumes:
   mysql:

```
3. 

```
`Wait for db connection ...
Connection established
first run - install kimai

Kimai installation running ...

 ! [NOTE] Database is existing and connection could be established              

                                                              
                    Application Migrations                    
                                                              

Migrating up to 20191116110124 from 20190729162655

  ++ migrating 20190730123324 (Creates user team and permission tables)

Migration 20190730123324 failed during Execution. Error The table with name 'kimai.kimai2_teams' already exists.
 [ERROR] Failed to set migration status: The table with name                    
         'kimai.kimai2_teams' already exists.                                   

Kimai2 ready
[Tue Dec 10 10:11:38.295282 2019] [mpm_prefork:notice] [pid 27] AH00163: Apache/2.4.38 (Debian) PHP/7.3.10 configured -- resuming normal operations
[Tue Dec 10 10:11:38.295345 2019] [core:notice] [pid 27] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'`
```
