### ISSUE TITLE
[BUG] 500 internal server error with apache-1.30.11-prod

### ISSUE THREAD

**Issue by klangborste** [tobybatch/kimai2#498]
**Describe the bug**
After the last update from the kimai apache image with the tag "apache2" and the image name "kimai/kimai2:apache" I get again an 500 internal server error.
After a rollback to the container image https://hub.docker.com/layers/kimai/kimai2/apache-1.30.6-prod/images/sha256-aeda8a97c08e2a04e27a0d9277215f4061dd27c92daccb337cb9ae171adc8694?context=explore it works fine again.

**To Reproduce**
Steps to reproduce the behaviour:
1. Update to [apache-1.30.11-prod](https://hub.docker.com/layers/kimai/kimai2/apache-1.30.11-prod/images/sha256-a8df61f626dfb9f03246fb8b4a956f3793e91c160c18a9d7f3e5ed6a34c8b9e5?context=explore)
2. Open Kimai UI web interface
3. See the error from screenshot:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/25405503/227561194-655393ca-38e4-4a3f-803f-8acc7c69fd04.png">

**Server**
 - OS:  Debian 11 (bullseye)
 - Docker version:  23.0.1, build a5ee5b1
 - Docker compose version: 1.29.2

**Command used to run the container**
 -   docker-compose pull && docker-compose up -d --remove-orphans --build
 -  "image: kimai/kimai2:apache" used

**Docker compose file (with passwords redacted)**

```yaml
# Kimai - Time Tracking
  kimai:
    container_name: kimai
    image: kimai/kimai2:apache
    #image: kimai/kimai2:apache-1.30.11-prod
    restart: always
    networks:
      - kimai_net
    volumes:
      - $DOCKERDIR/kimai/templates:/opt/kimai/var/invoices
    ports:
      - "8001:8001"
    depends_on:
        - kimai-mariadb
    environment:
      - DATABASE_URL=$DB_STRING
      - TRUSTED_HOSTS=$TRUSTED_HOSTS
```

**Additional context**
Perhaps it belongs to the ticket what I had already set once: https://github.com/kimai/kimai/issues/3788
