### ISSUE TITLE
Question about custom invoice template on 2.0.10

### ISSUE THREAD

**Issue by klangborste** [tobybatch/kimai2#500]
Hello together,

I updated my Kimai from "1.30.11-prod" to "2.0.10-prod" running on docker-compose.
Before the update ("1.30.11-prod" ) a custom default twig template was used and it worked well, after the update it seems that either I run into a fallback to the new default twig template or the location where to store the custom templates changed.

**docker-compose.yml:**

```yaml
# Kimai - Time Tracking
  kimai:
    container_name: kimai
    image: kimai/kimai2:apache-latest
    restart: always
    networks:
      - kimai_net
    volumes:
      - $DOCKERDIR/kimai/templates:/opt/kimai/var/invoices
    ports:
      - "8001:8001"
    depends_on:
        - kimai-mariadb
    environment:
      - DATABASE_URL=$DB_URL
      - TRUSTED_HOSTS=$TRUSTED_HOSTS

  kimai-mariadb:
    container_name: kimai-mariadb
    image: mariadb:latest
    restart: always
    networks:
      - kimai_net
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/kimai/mariadb:/var/lib/mysql
    secrets:
      - db_kimai_database
      - db_kimai_user
      - db_kimai_password
      - db_kimai_rootpass
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_kimai_rootpass
      - MYSQL_USER_FILE=/run/secrets/db_kimai_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_kimai_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_kimai_database
```
Tried to explain my issue in another bug report, but was properly misunderstood: https://github.com/tobybatch/kimai2/issues/482

Is there in the new 2.0.x version of Kimai something changed for the custom templates what I have to keep in my mind? The documentation didn't help with that either: https://www.kimai.org/documentation/invoices.html#create-your-own-invoice-document. I tried also to reverse engineering a little bit and did some try & error to minimize the error vector, but at the moment I got a little bit lost. Is there somebody can give me a hint or push me in the right direction? Thanks in advance
