### ISSUE TITLE
[BUG] Reloading cache removes "www-data" ownership

### ISSUE THREAD

**Issue by TSmigielski** [tobybatch/kimai2#502]
### Bug description
After upgrading to the new version available on docker "2.0.10", I was getting the 500 http code. It took me about 2/3 hours to figure out that: Reloading the cache changes both the owner and group to root, and resets the permissions of the "kimai/var/cache/pro_" and "kimai/var/cache/prod" directories.

As a one time deal, this wouldn't be that bad, to simply write 3 commands in the container to fix this,
these 3 for context:
```bash
chown -R :www-data
chmod -R g+r
chmod -R g+rw var/
```
But it will get annoying with every server restart, which happens for me roughly twice per month for various reasons. Of course this is a problem because Kimai reloads the cache on startup, and docker doesn't hold the state of a container when shutting down. 

### Desktop (please complete the following information):
 - OS: Fedora Linux 36 (Cloud Edition)
 - Docker version: docker-ce.x86_64 3:23.0.3-1.fc36
 - Docker compose version: docker-compose-plugin.x86_64 2.17.2-1.fc36

### Command used to run the container
 - docker compose start
 - docker compose up

### Docker compose file
```yaml
services:
  kimai:
    container_name: kimai
      image: kimai/kimai2:apache-2.0.10-prod
      volumes:
        - data:/opt/kimai/var
        - /opt/docker/kimai/config/local.yaml:/opt/kimai/config/packages/local.yaml
        - /opt/docker/kimai/config/php-memory-limit.ini:/usr/local/etc/php/conf.d/php-memory-limit.ini
        - /opt/docker/kimai/plugins/:/opt/kimai/var/plugins/
      ports:
        - 8001:8001
      environment:
        - ADMINMAIL=[redacted]
        - ADMINPASS=[redacted]
        - DATABASE_URL=[redacted]
        - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,[redacted domain]
      restart: unless-stopped

volumes:
  data:
```
