### ISSUE TITLE
[BUG] TOTP QR Code is not visible via tobybatch/nginx-fpm-reverse-proxy

### ISSUE THREAD

**Issue by DunklerPhoenix** [tobybatch/kimai2#506]
**Describe the bug**
Heho
I opened this issue here https://github.com/kimai/kimai/issues/3983
The TOTP QR Code for the user is missing.
@kevinpapst tested it in the Demo system and the QR Code works. So the only possible point where the problem comes from should be this container. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Throw the docker compose on host (with kimai/kimai2:fpm-2.0.14-prod)
2. go into kimai2 -> Profile -> TOTP
3. see the missing QR Code

**Desktop (please complete the following information):**
 - OS: Windows
 - Docker version: 23.0.4
 - Docker compose version: 2.17.2 (plugin)

**Docker compose file (with passwords redacted)**

```yaml
version: '3.8'
services:

  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    hostname: 'kimai_proxy'
    ports:
      - "3308:80"
    volumes:
      - type: bind
        source: /home/user/_files/kimai/public
        target: /opt/kimai/public
        read_only: true
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    labels: 
      traefik.enable: "true"
      traefik.docker.network: "network"
      traefik.http.routers.kimai.entrypoints: "https"
      traefik.http.routers.kimai.middlewares: "authelia@file"
      traefik.http.routers.kimai.rule: "Host(`domain`)"
      traefik.http.routers.kimai.tls.certresolver: "letsencrypt-tls"
      traefik.http.routers.kimai.tls: "true"
      traefik.http.routers.kimai-api.entrypoints: "https"
      traefik.http.routers.kimai-api.tls: "true"
      traefik.http.routers.kimai-api.tls.certresolver: "letsencrypt-tls"
      traefik.http.routers.kimai-api.rule: "Host(`domain`) && PathPrefix(`/api`)"
      traefik.http.services.kimai.loadbalancer.server.port: "80"

  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:fpm-2.0.14-prod
    hostname: 'kimai'
    environment:
      - MAILER_URL=smtp://postfix:25?encryption=&auth_mode=
      - MAILER_FROM=bardogs@kartoffel.email
      - DATABASE_URL=mysql://kimai:PASSSSSS@mysql/kimai
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,domain
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/user/_files/kimai/var
        target: /opt/kimai/var
      - type: bind
        source: /home/user/_files/kimai/public
        target: /opt/kimai/public
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z

networks:
  default:
    name: network
    external: true
```

**Additional context**
![CqzEjPizZD](https://user-images.githubusercontent.com/1261305/233632643-44510cf9-a35b-45ac-a5ee-322fa04efc31.png)
