### ISSUE TITLE
[BUG] Emails not working

### ISSUE THREAD

**Issue by vpanchal-code** [tobybatch/kimai2#516]
**Describe the bug**
Password reset emails are not working. 
Not sure what the issue is, postfix is not showing anything in the docker logs

**Docker compose file (with passwords redacted)**

```yaml
version: "3.0"
networks:
  br0:
    name: br0
    external: true
volumes:
  kimaivar:
    name: kimaivar
    external: true
  kimaipublic:
    name: kimaipublic
    external: true
  kimaimysql:
    name: kimaimysql
    external: true
services:
  kimai_nginx:
    image: tobybatch/nginx-fpm-reverse-proxy:latest
    container_name: kimai_nginx
    ports:
      - 8008:80
    volumes:
      - kimaipublic:/opt/kimai/public:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-America/New_York}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS}
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test: wget --spider 192.168.1.4/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      br0:
        ipv4_address: 172.18.5.199
  kimai:
    image: kimai/kimai2:fpm-latest
    container_name: kimai
    depends_on:
      kimai_db:
        condition: service_healthy
    environment:
      - ADMINMAIL=${ADMINMAIL}
      - ADMINPASS=${ADMINPASS}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@kimai_db/${MYSQL_DATABASE}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS}
      - TZ=${TZ:-America/New_York}
      - memory_limit=512M
    volumes:
      - kimaipublic:/opt/kimai/public
      - kimaivar:/opt/kimai/var
      # - /home/docker/kimai/local.yaml:/opt/kimai/config/packages/local.yaml
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: 172.18.5.198
  kimai_phpmyadmin:
    image: phpmyadmin:latest
    container_name: kimai_phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      br0:
        ipv4_address: 172.18.5.197
  kimai_swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: kimai_swagger
    ports:
      - 8087:8080
    volumes:
      - /home/docker/kimai/swagger.json:/swagger.json
    environment:
      - SWAGGER_JSON=/swagger.json
    networks:
      br0:
        ipv4_address: 172.18.5.196
  kimai_postfix:
    image: catatnight/postfix:latest
    container_name: kimai_postfix
    environment:
      maildomain: simplementix.com
      smtp_user: ${SIMPLE_SMTP_USER}:${SIMPLE_SMTP_PASS}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ:-America/New_York}
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: 172.18.5.195
  kimai_db:
    image: mysql:5.7
    container_name: kimai_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-America/New_York}
    volumes:
      - kimaimysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      br0:
        ipv4_address: 172.18.5.194
```

**Additional context**
