### ISSUE TITLE
[BUG] Failed to validate database. Invalid platform version.

### ISSUE THREAD

**Issue by pbek** [tobybatch/kimai2#531]
**Describe the bug**
Watchtower just updated my `kimai/kimai2:apache` container to `kimai/kimai2:apache@sha256:b9f112affef9301c6be8e16e9b75bed13131fc9f5f38793f85e61f6843d5e28e`.

When starting the new container, there immediately was an error:

```
Kimai updates running ...

=========================

 [ERROR] Failed to validate database.                                           

                                                                                

         Invalid platform version "" specified. The platform version has to be  

         specified in the format:                                               

         "<major_version>.<minor_version>.<patch_version>".                     
```

This error is repeated on every database access.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the container `kimai/kimai2:apache` (I'm not if this only occurs on existing installations)
2. Get above error messages

**Docker compose file (with passwords redacted)**

```yaml
  kimai:
    image: kimai/kimai2:apache
    depends_on:
      - kimai-mysql
    volumes:
      - kimai-var:/opt/kimai/var
      - ./kimai/local.yaml:/opt/kimai/config/packages/local.yaml
    restart: unless-stopped
    networks:
      - kimai
      - traefik
    environment:
      - TZ=Europe/Vienna
      - TRUSTED_HOSTS=localhost,127.0.0.1,time.domain.com
      - ADMINMAIL=my@email.com
      # We need to set user and group because of https://github.com/tobybatch/kimai2/issues/456
      - USER_ID=33
      - GROUP_ID=33
    env_file:
      - ./kimai/variables-kimai.env
    labels:
      - traefik.http.routers.kimai.rule=Host(`time.domain.com`)
      - traefik.http.routers.kimai.tls.certresolver=default
      - traefik.http.routers.kimai.tls=true
      - traefik.http.services.kimai.loadbalancer.server.port=8001
      - traefik.docker.network=server_traefik
```
