### ISSUE TITLE
[BUG] Error 500 at plugins

### ISSUE THREAD

**Issue by dominikjas** [tobybatch/kimai2#534]
**Describe the bug**
After I updated the container and edited the DATABASE_URL it seemed like everything is working, but when I  try to access the plugins I get a Error 500. The log shows the following:

```
[2023-08-22T19:33:08.106173+00:00] php.CRITICAL: Uncaught Error: Call to undefined method App\Event\PageActionsEvent::setPayload() {"exception":"[object] (Error(code: 0): Call to undefined method App\\Event\\PageActionsEvent::setPayload() at /opt/kimai/var/plugins/KioskBundle/EventSubscriber/PluginActionsSubscriber.php:65)"} []
[2023-08-22T19:33:08.107800+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "setPayload" of class "App\Event\PageActionsEvent". Did you mean to call "getPayload"?" at /opt/kimai/var/plugins/KioskBundle/EventSubscriber/PluginActionsSubscriber.php line 65 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"setPayload\" of class \"App\\Event\\PageActionsEvent\".\nDid you mean to call \"getPayload\"? at /opt/kimai/var/plugins/KioskBundle/EventSubscriber/PluginActionsSubscriber.php:65)"} []
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Login to Kimai
2. Click on Plugins (german: "Erweiterungen")
![image](https://github.com/tobybatch/kimai2/assets/83553492/c9c4ee35-67e6-4a26-929f-c6b36edb7d2d)
![image](https://github.com/tobybatch/kimai2/assets/83553492/28e842a2-b829-4e1f-92e2-50feae994564)

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome

Server:
- Debian 11
 - Docker version: 24.0.4, build 3713ee1
 - Docker compose version: 1.29.2, build 5becea4c

**Docker compose file (with passwords redacted)**

```

version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    hostname: kunde-zeiterfassung-mysql
    volumes:
      - kimai-mysql:/var/lib/mysql
      - kimai-custom:/opt/kimai/config/packages/
      - kimai-apache2:/etc/apache2/
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=***
      - MYSQL_ROOT_PASSWORD=***
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      kunde-zeiterfassung_network:
        ipv4_address: 172.16.1.11

  kimai:
    image: kimai/kimai2:apache-latest
    hostname: kunde-zeiterfassung-kimai
    volumes:
      - kimai-var:/opt/kimai/var
      - kimai-custom:/opt/kimai/config/packages/
      - kimai-apache2:/etc/apache2/
    expose:
      - 8001
    environment:
      - ADMINMAIL=***
      - ADMINPASS=***
      - DATABASE_URL=mysql://kimaiuser:***@172.16.1.11/kimai?charset=utf8&serverVersion=5.7
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,zeit.kunde.de
      - TIMEZONE=Europe/Berlin
    restart: unless-stopped
    networks:
      kunde-zeiterfassung_network:
        ipv4_address: 172.16.1.12

volumes:
  kimai-var:
  kimai-mysql:
  kimai-custom:
  kimai-apache2:

networks:
  kunde-zeiterfassung_network:
    external: true
```
