### ISSUE TITLE
Kimai with Traefik as reverse proxy redirects to http when only https is set-up in docker-compose.yml

### ISSUE THREAD

**Issue by lustrant** [tobybatch/kimai2#548]
Hello,
based on your compose/traefik/docker-compose.yml  I have created my own docker-compose.yml file, however I have commented out the section with the redirect from HTTP to HTTPS.

When accessing https://kimai.doma.pawouk I get redirected to http://kimai.doma.pawouk/cs_CZ/login where its stuck, because I dont have Traefik configured to handle non-https requests at all.

When I enable the HTTP section, it works. However, I would like to have it without HTTP completely. Is it possible at all?

**My docker-compose.yml is as follows**

```yaml
version: '3.5'
services:

  kimai:
    image: kimai/kimai2:apache-latest
    environment:
      APP_ENV: prod
      ADMINMAIL: ${KIMAI_ADMIN_MAIL}
      ADMINPASS: ${KIMAI_ADMIN_PASS}
      DATABASE_URL: mysql://${SQL_USER_NAME}:${SQL_USER_PASS}@${SQL_DB_HOST}/${SQL_DB_NAME}
      TRUSTED_HOSTS: nginx,localhost,127.0.0.1,traefik,kimai.${HOST}
      TRUSTED_PROXIES: nginx,localhost,127.0.0.1,traefik,kimai.${HOST}
      memory_limit: 500M
    networks:
      - sit-databaze
      - sit-proxy
    volumes:
      - ${PWD}/data/public:/opt/kimai/public
      # - var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: sit-proxy

      # HTTP -> HTTPS redirect middleware  -- DISABLED
#      traefik.http.routers.kimai-redirect.entrypoints: web
#      traefik.http.routers.kimai-redirect.rule: Host(`kimai.${HOST}`)
#      traefik.http.routers.kimai-redirect.middlewares: httpsredirect
#      traefik.http.middlewares.httpsredirect.redirectscheme.scheme: https

      # HTTPS -> Service router
      traefik.http.routers.kimai.entrypoints: websecure
      traefik.http.routers.kimai.rule: Host(`kimai.${HOST}`)
      traefik.http.routers.kimai.tls: true
      traefik.http.routers.kimai.service: kimai

      # Service
      traefik.http.services.kimai.loadbalancer.server.port: 8001
      traefik.http.services.kimai.loadbalancer.server.scheme: http
      traefik.http.services.kimai.loadbalancer.passHostHeader: true

networks:
  sit-proxy:
    external: true
  sit-databaze:
    external: true
```

**My .env file is as follows**

```ini
HOST=doma.pawouk

KIMAI_ADMIN_MAIL=admin@kimai.local
KIMAI_ADMIN_PASS=changemeplease

SQL_DB_HOST=mariadb
SQL_DB_NAME=kimai

SQL_USER_NAME=kimai
SQL_USER_PASS=password
```
