### ISSUE TITLE
[BUG] Error submitting form according to language

### ISSUE THREAD

**Issue by Hansanghyeon** [tobybatch/kimai2#554]
If the language is in Korean, the time setting is 'A hh:mm.' If you spend time 'A hh:mm' in the API, you will be disappointed.

<img width="1214" alt="image" src="https://github.com/tobybatch/kimai2/assets/42893446/4f12a123-2f3a-4a78-ba77-1a56f2b90f06">

And if you change the language setting to English and call the API, it will work normally.

I think I need to modify the API Velocity according to the i18n time setting.

**Desktop (please complete the following information):**
 - `ubuntu 22.04LTS`
 - `Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1`
 - `Docker Compose version v2.23.0`

**Command used to run the container**
 - `docker compose up -d`

**Docker compose file (with passwords redacted)**

```yaml
version: '3.9'
services:
  sqldb:
    image: mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #ports:
    #  - 3336:3306
    volumes:
      - ./db:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:apache
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai?charset=utf8&serverVersion=5.7.40
      - MAILER_URL=smtp://mailer:1025
      - MAILER_FROM=no-replay@beeclover.pro
    volumes:
      - ./public:/opt/kimai/public
      # - ./var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped

  # swagger:
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - 8082:8080
  #   # volumes:
  #   #   - ./swagger.json:/swagger.json
  #   environment:
  #     - SWAGGER_JSON=/swagger.json

  mailer:
    image: schickling/mailcatcher
    ports:
      - "${MAILER_SMTP_PORT:-1025}:1025"
      - "${MAILER_ADMIN_PORT:-1080}:1080"

```
