### ISSUE TITLE
[BUG] composer require symfony/sendgrid-mailer fails

### ISSUE THREAD

**Issue by amammes** [tobybatch/kimai2#563]
Hi, I am trying to add sendgrid support and kimai instructions say that I need to add the symfony/sendgrid-mailer package. However, 
"composer require symfony/sendgrid-mailer" fails with the following output:
```
root@d06b1d3c4ad0:/var/www/html# cd /opt/kimai
root@d06b1d3c4ad0:/opt/kimai# composer require symfony/sendgrid-mailer

In ArtifactRepository.php line 76:
                                                                                                               
  RecursiveDirectoryIterator::__construct(var/packages/): Failed to open directory: No such file or directory  
                                                                                                               
require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

I checked out /opt/kimai/composer.json and it has the following repository which does not exist on the file system.
```
"repositories": [
        {
            "type": "artifact",
            "url": "var/packages/"
        }
    ],
```

I am sorry but I am not experienced in php and much less with composer parameters, but I believe the repository path is incorrect in /opt/kimai/composer.json

**Desktop (please complete the following information):**
 - Hypervisor is Proxmox 8.1. Docker host is Debian 12 bookworm.
 - Docker version: 
```
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Command used to run the container**
docker compose up -d

**Docker compose file (with passwords redacted)**
```
version: '3.5'
services:

  mysql:
    image: mysql:5.7
    container_name : kimai1-mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=redacted
      - MYSQL_ROOT_PASSWORD=redacted
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - default

  kimai:
    image: kimai/kimai2:apache
    container_name : kimai1-kimai
    volumes:
      - ./kimai/var:/opt/kimai/var
    ports:
      - 8022:22
    environment:
      - ADMINMAIL=redacted
      - ADMINPASS=redacted
      - "DATABASE_URL=mysql://kimaiuser:redacted@kimai1-mysql/kimai?charset=utf8"
      - MAILER_FROM=redacted@example.com
      - MAILER_URL=sendgrid+smtp://redacted_senddrid_key@default
      - TRUSTED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default
      - default

  phpmyadmin:
    image: phpmyadmin
    container_name : kimai1-phpmyadmin
    restart: always
    environment:
      PMA_HOST: kimai1-mysql
      PMA_ABSOLUTE_URI: redacted
      UPLOAD_LIMIT: 768M
      PMA_PORT: 3306
    networks:
      - nginx-proxy-manager_default
      - default

networks:
  nginx-proxy-manager_default:
    external: true
  default:

```
