### ISSUE TITLE
[BUG] Additional properties are not allowed ('start period' was unexpected) when using docker-compose

### ISSUE THREAD

**Issue by urinal-cake** [tobybatch/kimai2#64]
This may not fully be a bug, but instead a case of User Error. However, if it's not, then the issue I'm running into may be remedied with better instructions.

**Describe the bug**
When starting the docker containers with the command 'docker-compose up -d' docker states that the docker-compose file is invalid because all three services with healthcheck parameters defined in the docker-compose, have invalid syntax.

**To Reproduce**
Steps to reproduce the behaviour:
1. `sudo git clone https://github.com/tobybatch/kimai2.git kimai`
2. `sudo cd /opt/kimai`
3.  `docker-compose up -d`
4. Notice the following errors are displayed: 

> ERROR: The Compose file './docker-compose.yml' is invalid because:                                       > services.kimai.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
> services.nginx.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
> services.sqldb.healthcheck value Additional properties are not allowed ('start_period' was unexpected)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 bionic
 - Docker version: 19.03.5
 - Docker compose version: 1.17.1

**Command used to run the container**
 - `docker-compose up -d`

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -pchangemeplease ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3 

  nginx:
    build: compose
    ports:
      - 8001:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - kimai
    volumes:
      - public:/opt/kimai/public
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1 
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3 

  kimai:
    image: kimai/kimai2:fpm-alpine-1.5-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=localhost
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    restart: unless-stopped
    restart: always

volumes:
    var:
    public:
```

**Additional context**
Commenting out the start_period parameter made docker correctly pull, build and start kimai
