### ISSUE TITLE
[BUG] "ERROR [internal/git-dev 1/2] FROM registry/image-name:version" when running build

### ISSUE THREAD

**Issue by urinal-cake** [tobybatch/kimai2#76]
**Describe the bug**
In an attempt to build a local image of kimai2 on the **saml** branch, I am running the build.sh script inside of the bin folder. Having only made changes to the nginx.conf file and docker-compose file, after running `sudo bin/build.sh saml` from the tobybatch/kimai2 local directory, a number of errors are produced.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone tobybatch/kimai2 to a directory
2. Execute `sudo bin/build.sh saml` to attempt to build a kimai2 image
3. Notice the [errors listed in this gist](https://gist.github.com/urinal-cake/f3d6b87da475b6977b4b3fc8fb650b3f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Docker version: Docker version 19.03.5, build 633a0ea838
 - Docker compose version: docker-compose version 1.17.1, build unknown

**Command used to run the container**
 -  `sudo bin/build.sh saml`

**Docker compose file (with passwords redacted)**

```yaml
version: '3.4'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaidbroot
      - MYSQL_PASSWORD=<REDACTED>
      - MYSQL_ROOT_PASSWORD=<REDACTED>
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -pchangemeplease ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    build: compose
    ports:
      - 8001:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - kimai
    volumes:
      - public:/opt/kimai/public
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:fpm-alpine-1.5-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=timesheet.punyhuman.com
      - ADMINMAIL=ops@punyhuman.com
      - ADMINPASS=<REDACTED>
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
      - /opt/punykimai/config/local.yaml:/opt/kimai/config/packages/local.yaml
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: punyhuman.com
      smtp_user: kimai:kimai
    restart: unless-stopped
    restart: always

volumes:
    var:
    public:
```

**Additional context**
I apologize if this isn't exactly a defect with something in this repository. It's very likely that it is user error, and I'm not an expert at docker and docker-compose, so I apologize in advance if that is the case. I have done my best to research what the issues could be in the Gist linked above, but cannot identify where this has happened similarly.
