### ISSUE TITLE
[BUG] nginx configuration is not mounted

### ISSUE THREAD

**Issue by heeen** [tobybatch/kimai2#86]
**Describe the bug**
the nginx site config is not mounted correctly into the container

**To Reproduce**
Steps to reproduce the behaviour:

docker-compose stop
docker-compose rm
docker system purge --volumes
docker-compose up
```
/srv/kimai2# docker exec kimai2_nginx_1 grep try_files /etc/nginx/conf.d/default.conf
        try_files $uri $uri/ /index.php;
/srv/kimai2# grep try_files compose/nginx_site.conf 
        try_files $uri $uri/ /index.php$is_args$args;
```
**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3
 - Docker version: 19.03.5, build 633a0ea838
 - Docker compose version: 1.25.1-rc1, build d92e9bee

**Command used to run the container**
 - docker-compose up -d

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=XXX
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -pXXX ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3 

  nginx:
    build: compose
    ports:
      - 8001:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - kimai
    volumes:
      - public:/opt/kimai/public
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1 
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3 

  kimai:
    image: kimai/kimai2:fpm-alpine-1.5-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=XXX,localhost,nginx
      - ADMINMAIL=XXX
      - ADMINPASS=XXX
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: XXX
      smtp_user: kimai:kimai
    restart: unless-stopped
    restart: always

volumes:
    var:
    public:

```

**Additional context**
